-- Part C: Ecology -- batch 2/5
INSERT INTO quiz_questions (event_id, topic, subtopic, question, options, correct_index, correct_answer_text, explanation, difficulty, question_type, points, source_tournament, ai_generated)
VALUES
INSERT INTO quiz_questions (event_id, topic, subtopic, question, options, correct_index, correct_answer_text, explanation, difficulty, question_type, points, source_tournament, ai_generated)
VALUES
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Ocean Chemistry', NULL, 'What is the primary mechanism by which increased atmospheric CO2 affects ocean acidity?', '["CO2 reacts with water to form carbonic acid", "CO2 blocks sunlight, reducing photosynthesis", "CO2 enhances biological calcification", "CO2 decreases the albedo effect"]'::jsonb, 0, 'CO2 reacts with water to form carbonic acid', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Ecosystem Services', NULL, 'The Millennium Ecosystem Assessment categorized ecosystem services into which four main types?', '["Supporting, provisioning, regulating, and cultural", "Nutrient cycling, photosynthesis, decomposition, and energy flow", "Carbon sequestration, biodiversity, water filtration, and soil formation", "Primary production, secondary production, trophic transfer, and respiration"]'::jsonb, 0, 'Supporting, provisioning, regulating, and cultural', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Biodiversity', NULL, 'What does a high beta diversity value indicate?', '["High species richness within a single site", "Low turnover of species across habitats", "High turnover of species between different habitats", "Even distribution of individuals within a community"]'::jsonb, 2, 'High turnover of species between different habitats', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Fisheries Management', NULL, 'In the context of fisheries, what does maximum sustainable yield (MSY) assume?', '["That fish populations do not interact with other species", "That populations grow logistically and have a fixed carrying capacity", "That harvesting does not impact reproductive success", "That marine reserves are unnecessary for conservation"]'::jsonb, 1, 'That populations grow logistically and have a fixed carrying capacity', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Biomes', NULL, 'Which biome is predicted to be most impacted by climate change in terms of biodiversity loss?', '["Tropical rainforests", "Boreal forests", "Temperate grasslands", "Deep-sea ecosystems"]'::jsonb, 2, 'Temperate grasslands', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Island Biogeography', NULL, 'What is the relationship between island size and species richness according to the theory of island biogeography?', '["Species richness decreases with increased island size", "Species richness increases with increased island size", "Island size has no impact on species richness", "Only proximity to the mainland influences species richness"]'::jsonb, 1, 'Species richness increases with increased island size', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Deep-Sea Ecosystems', NULL, 'Why do organisms living in deep-sea hydrothermal vents rely on chemosynthesis rather than photosynthesis?', '["Sunlight cannot penetrate to these depths", "There is an abundance of nutrients from surface runoff", "Deep-sea organisms lack photosynthetic pigments", "Photosynthesis is inefficient in saline environments"]'::jsonb, 0, 'Sunlight cannot penetrate to these depths', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Soil Ecology', NULL, 'What is the primary ecological role of earthworms in soil ecosystems?', '["Nitrogen fixation", "Decomposition and nutrient cycling", "Pollination", "Carbon sequestration"]'::jsonb, 1, 'Decomposition and nutrient cycling', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Diversity Indices', NULL, 'How does the Simpson Index differ from the Shannon-Wiener Index?', '["The Simpson Index emphasizes species richness over evenness", "The Shannon-Wiener Index ignores species evenness", "The Simpson Index measures only the number of species in a community", "The Shannon-Wiener Index accounts for rare species more than the Simpson Index"]'::jsonb, 3, 'The Shannon-Wiener Index accounts for rare species more than the Simpson Index', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Niche Theory', NULL, 'What is the key difference between fundamental and realized niches?', '["The fundamental niche accounts for competition, while the realized niche does not", "The realized niche is the actual space an organism inhabits due to interactions with other species", "Fundamental niches are determined by biotic factors, while realized niches are purely abiotic", "Realized niches exist only in disturbed ecosystems"]'::jsonb, 1, 'The realized niche is the actual space an organism inhabits due to interactions with other species', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false);
