-- Part D: Ecology -- batch 3/5
INSERT INTO quiz_questions (event_id, topic, subtopic, question, options, correct_index, correct_answer_text, explanation, difficulty, question_type, points, source_tournament, ai_generated)
VALUES
INSERT INTO quiz_questions (event_id, topic, subtopic, question, options, correct_index, correct_answer_text, explanation, difficulty, question_type, points, source_tournament, ai_generated)
VALUES
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Grassland Ecology', NULL, 'Which soil type is most characteristic of temperate grasslands?', '["Spodosol", "Histosol", "Mollisol", "Oxisol"]'::jsonb, 2, 'Mollisol', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Grassland Ecology', NULL, 'What primary factor limits tree growth in grasslands?', '["Low precipitation", "High herbivore diversity", "Poor soil aeration", "High nitrogen availability"]'::jsonb, 0, 'Low precipitation', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Grassland Ecology', NULL, 'C4 grasses have an advantage over C3 grasses in:', '["Cold, wet environments", "High temperature, low CO2 environments", "Nutrient-rich, shaded forests", "High-latitude tundra regions"]'::jsonb, 1, 'High temperature, low CO2 environments', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Grassland Ecology', NULL, 'Fire plays a critical role in grassland ecology because it:', '["Reduces nitrogen availability", "Encourages woody plant succession", "Maintains open landscapes by preventing tree encroachment", "Increases soil alkalinity"]'::jsonb, 2, 'Maintains open landscapes by preventing tree encroachment', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Grassland Ecology', NULL, 'The dominant grassland biome in North America is the:', '["Pampas", "Steppe", "Prairie", "Veld"]'::jsonb, 2, 'Prairie', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Grassland Ecosystems', NULL, 'Which of the following grassland regions is maintained by seasonal flooding?', '["Serengeti", "Everglades", "Llanos", "Great Plains"]'::jsonb, 2, 'Llanos', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Grassland Ecology', NULL, 'How do grasses primarily adapt to grazing pressure?', '["By producing secondary metabolites that deter herbivory", "By developing deep root systems for water access", "By growing from basal meristems rather than apical buds", "By increasing leaf thickness to minimize water loss"]'::jsonb, 2, 'By growing from basal meristems rather than apical buds', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Grassland Ecology', NULL, 'What is the primary mechanism driving species diversity in grasslands?', '["High annual precipitation", "Frequent disturbance events such as grazing and fire", "High soil nutrient levels", "Strong interspecies competition"]'::jsonb, 1, 'Frequent disturbance events such as grazing and fire', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Grassland Ecosystems', NULL, 'The Serengeti ecosystem is famous for its large-scale migration of which herbivore?', '["American bison", "Gazelle", "Przewalski''s horse", "Wildebeest"]'::jsonb, 3, 'Wildebeest', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Grassland Degradation', NULL, 'Which of the following factors is a major contributor to grassland desertification?', '["Increased native herbivore populations", "Overgrazing by livestock", "Expansion of wetlands", "Increased CO2 fertilization"]'::jsonb, 1, 'Overgrazing by livestock', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false);
