-- Part O: Wind Power -- batch 2/3
INSERT INTO quiz_questions (event_id, topic, subtopic, question, options, correct_index, correct_answer_text, explanation, difficulty, question_type, points, source_tournament, ai_generated)
VALUES
INSERT INTO quiz_questions (event_id, topic, subtopic, question, options, correct_index, correct_answer_text, explanation, difficulty, question_type, points, source_tournament, ai_generated)
VALUES
  ((SELECT id FROM events WHERE name = 'Wind Power'), 'Electrical Systems', NULL, 'A device that resists changes in current flow is called a(n):', '["Resistor", "Inductor", "Capacitor", "Battery"]'::jsonb, 1, 'Inductor', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Wind Power'), 'Electrical Systems', NULL, 'The formula P = V × I × cosφ represents:', '["Reactive power", "Active power", "Apparent power", "Magnetic field strength"]'::jsonb, 1, 'Active power', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Wind Power'), 'Energy Storage', NULL, 'What is the primary reason energy storage is needed for wind and solar power?', '["To reduce energy costs", "To provide backup power during low production times", "To eliminate the need for batteries", "To increase fossil fuel usage"]'::jsonb, 1, 'To provide backup power during low production times', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Wind Power'), 'Energy Conversion', NULL, 'What type of solar cell is most efficient?', '["Polycrystalline silicon", "Monocrystalline silicon", "Amorphous silicon", "Cadmium telluride"]'::jsonb, 1, 'Monocrystalline silicon', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Wind Power'), 'Energy Storage', NULL, 'What is the primary function of the electrolyte in a battery?', '["To store energy", "To allow ion movement between electrodes", "To prevent electricity flow", "To increase the reliability of the battery"]'::jsonb, 1, 'To allow ion movement between electrodes', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Wind Power'), 'Energy Conversion', NULL, 'Which energy source does a concentrated solar power plant use?', '["Photovoltaic panels", "Molten salt storage", "Fossil fuels", "Geothermal heat"]'::jsonb, 1, 'Molten salt storage', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Wind Power'), 'Energy Conversion', NULL, 'What is the purpose of control rods in a nuclear reactor?', '["To increase temperature", "To speed up nuclear fission", "To regulate the reaction and absorb excess neutrons", "To store nuclear waste"]'::jsonb, 2, 'To regulate the reaction and absorb excess neutrons', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Wind Power'), 'Electrical Systems', NULL, 'What is the primary function of power electronics?', '["To generate electricity", "To convert and control electrical power for various applications", "To transmit mechanical energy", "To store electrical energy in batteries"]'::jsonb, 1, 'To convert and control electrical power for various applications', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Wind Power'), 'Electrical Systems', NULL, 'Which component in power electronics acts as a switch that can rapidly turn on and off?', '["Capacitor", "Inductor", "Power Semiconductor", "Transformer"]'::jsonb, 2, 'Power Semiconductor', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Wind Power'), 'Energy Conversion', NULL, 'Which type of converter is used to convert DC power into AC power?', '["Rectifier", "Chopper", "Inverter", "Transformer"]'::jsonb, 2, 'Inverter', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false);
