-- Part B: Ecology -- batch 1/5
INSERT INTO quiz_questions (event_id, topic, subtopic, question, options, correct_index, correct_answer_text, explanation, difficulty, question_type, points, source_tournament, ai_generated)
VALUES
INSERT INTO quiz_questions (event_id, topic, subtopic, question, options, correct_index, correct_answer_text, explanation, difficulty, question_type, points, source_tournament, ai_generated)
VALUES
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Metabolic Theory', NULL, 'The metabolic theory of ecology suggests that metabolic rates scale with body mass according to what exponent?', '["1.0", "-1.5", "-0.75", "0.25"]'::jsonb, 2, '-0.75', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Competition Models', NULL, 'In Lotka-Volterra competition models, what does a competition coefficient (α) greater than 1 indicate?', '["Intraspecific competition is stronger than interspecific competition", "Interspecific competition is stronger than intraspecific competition", "The populations are at equilibrium", "The species cannot coexist"]'::jsonb, 1, 'Interspecific competition is stronger than intraspecific competition', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Energy Flow', NULL, 'According to the Lindeman efficiency rule, approximately what percentage of energy is transferred between trophic levels?', '["50%", "10%", "25%", "1%"]'::jsonb, 1, '10%', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Survivorship Curves', NULL, 'Which of the following is a defining characteristic of a Type III survivorship curve?', '["High survival in early life stages, declining in later stages", "Constant mortality throughout life", "High mortality in early life, with survival increasing for older individuals", "Equal mortality across all age groups"]'::jsonb, 2, 'High mortality in early life, with survival increasing for older individuals', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Population Dynamics', NULL, 'The Allee effect describes:', '["A negative density dependence in population growth", "The impact of competition on carrying capacity", "The maximum reproductive potential of an organism", "A positive density dependence in population growth at low population sizes"]'::jsonb, 3, 'A positive density dependence in population growth at low population sizes', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Landscape Ecology', NULL, 'In the context of landscape ecology, what is meant by "percolation threshold"?', '["The maximum amount of habitat loss before species extinction occurs", "The point at which landscape connectivity allows for continuous species dispersal", "The rate at which water infiltrates soil in an ecosystem", "The temperature at which an ecosystem undergoes succession"]'::jsonb, 1, 'The point at which landscape connectivity allows for continuous species dispersal', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Photosynthesis', NULL, 'The C4 photosynthetic pathway is advantageous under which conditions?', '["High CO2 and low oxygen", "Low temperature and high moisture", "High temperature and low CO2", "High salinity and low nitrogen availability"]'::jsonb, 2, 'High temperature and low CO2', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Species-Area Relationship', NULL, 'Which of the following equations describes species-area relationships?', '["S = cA^z", "dN/dt = rN(1 - N/K)", "H'' = -\u03a3(pi ln pi)", "P = G + R"]'::jsonb, 0, 'S = cA^z', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Plant Ecology', NULL, 'The Janzen-Connell hypothesis suggests that:', '["Herbivory maintains plant diversity", "Seedling recruitment is suppressed near parent trees due to specialized predators", "Nutrient cycling efficiency increases with biodiversity", "Mycorrhizal associations drive forest succession"]'::jsonb, 1, 'Seedling recruitment is suppressed near parent trees due to specialized predators', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Aquatic Ecology', NULL, 'Which factor most influences primary productivity in freshwater lakes?', '["Phosphorus availability", "Iron deposition", "Wind speed", "Alkalinity"]'::jsonb, 0, 'Phosphorus availability', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false);
