-- Part M: Reach for the Stars -- batch 3/3
INSERT INTO quiz_questions (event_id, topic, subtopic, question, options, correct_index, correct_answer_text, explanation, difficulty, question_type, points, source_tournament, ai_generated)
VALUES
INSERT INTO quiz_questions (event_id, topic, subtopic, question, options, correct_index, correct_answer_text, explanation, difficulty, question_type, points, source_tournament, ai_generated)
VALUES
  ((SELECT id FROM events WHERE name = 'Reach for the Stars'), 'Binary Systems', NULL, 'In what type of star system is this type of supernova most likely to occur?', '["Single star systems with many gaseous planets", "Binary star systems with massive stars", "Binary star systems with low mass stars", "Binary star systems with a black hole"]'::jsonb, 2, 'Binary star systems with low mass stars', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Reach for the Stars'), 'Binary Systems', NULL, 'How does the frequency and intensity of dwarf novae compare to classical novae?', '["Dwarf novae are less intense and more frequent", "Dwarf novae are less intense and less frequent", "Dwarf novae are more intense and less frequent", "Dwarf novae are more intense and more frequent"]'::jsonb, 0, 'Dwarf novae are less intense and more frequent', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Reach for the Stars'), 'Binary Systems', NULL, 'Which type of X-ray binary system usually has a white dwarf as the accretor instead of a neutron star or black hole', '["Soft X-ray transients", "Low mass X-ray binary", "Intermediate mass X-ray binary", "Supersoft X-ray source"]'::jsonb, 3, 'Supersoft X-ray source', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Reach for the Stars'), 'Stellar Evolution', NULL, 'Which stage of stellar evolution begins when a low to intermediate mass star exhausts both the supply of hydrogen and helium in its core, being left with an inert core of carbon and oxygen?', '["Subgiant Branch", "Red Giant Branch", "Horizontal Branch", "Asymptotic Giant Branch"]'::jsonb, 3, 'Asymptotic Giant Branch', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false);
