-- Part K: Reach for the Stars -- batch 1/3
INSERT INTO quiz_questions (event_id, topic, subtopic, question, options, correct_index, correct_answer_text, explanation, difficulty, question_type, points, source_tournament, ai_generated)
VALUES
INSERT INTO quiz_questions (event_id, topic, subtopic, question, options, correct_index, correct_answer_text, explanation, difficulty, question_type, points, source_tournament, ai_generated)
VALUES
  ((SELECT id FROM events WHERE name = 'Reach for the Stars'), 'Stellar Classification', NULL, 'If stars A and B have the same luminosity, star A is twice as far away from Earth as star B, and the light coming from star A experiences the same amount of extinction as star B, the absolute magnitudes of the two stars are the same.', '["True", "False", "", ""]'::jsonb, 0, 'True', NULL, 'hard', 'true_false', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Reach for the Stars'), 'Stellar Classification', NULL, 'If the absolute magnitudes of two stars differ by 1.0, and they are the same distance to earth, then it means their absolute magnitudes must also differ by 1.0.', '["True", "False", "", ""]'::jsonb, 0, 'True', NULL, 'medium', 'true_false', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Reach for the Stars'), 'Binary Systems', NULL, 'The accretor of an X-ray binary system is usually a white dwarf.', '["True", "False", "", ""]'::jsonb, 0, 'True', NULL, 'medium', 'true_false', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Reach for the Stars'), 'Stellar Evolution', NULL, 'Stars with an initial mass around 0.7 M are generally unable to undergo a core helium flash.', '["True", "False", "", ""]'::jsonb, 0, 'True', NULL, 'hard', 'true_false', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Reach for the Stars'), 'Stellar Evolution', NULL, 'Stars with an initial mass around 7 M generally end their life in a core collapse supernova.', '["True", "False", "", ""]'::jsonb, 0, 'True', NULL, 'hard', 'true_false', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Reach for the Stars'), 'Stellar Classification', NULL, 'Class B stars have a higher surface temperature than class A stars.', '["True", "False", "", ""]'::jsonb, 1, 'False', NULL, 'easy', 'true_false', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Reach for the Stars'), 'Stellar Classification', NULL, 'Class F stars have a higher surface temperature than class G stars.', '["True", "False", "", ""]'::jsonb, 0, 'True', NULL, 'easy', 'true_false', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Reach for the Stars'), 'White Dwarfs', NULL, 'White dwarfs with larger radii are denser than white dwarfs with smaller radii.', '["True", "False", "", ""]'::jsonb, 1, 'False', NULL, 'hard', 'true_false', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Reach for the Stars'), 'Stellar Evolution', NULL, 'Only stars that are type O on the main sequence are massive enough to undergo core collapse supernovae.', '["True", "False", "", ""]'::jsonb, 1, 'False', NULL, 'hard', 'true_false', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Reach for the Stars'), 'Stellar Classification', NULL, 'A main sequence star with a mass of around 3 M belongs in spectral class A.', '["True", "False", "", ""]'::jsonb, 1, 'False', NULL, 'medium', 'true_false', 1, 'Badger Invitational 2025', false);
