-- ═══════════════════════════════════════════════════════════════
--  Migration 020: Import Badger Invitational 2025 Questions
--                  (Division B only)
--
--  Imports 136 questions extracted from the
--  Badger Invitational 2025 tournament tests.
--  Source: PDF/DOCX test documents
--  Events: Ecology, Meteorology, Optics,
--          Reach for the Stars, Wind Power
--  Batched in groups of 10 to avoid SQL editor timeouts.
-- ═══════════════════════════════════════════════════════════════


-- ─── 1. Create events not yet in the database ──────────────────
INSERT INTO events (name, type, team_size, icon, is_trial, season)
VALUES ('Ecology', 'study', 2, '🌿', true, '2025-2026')
ON CONFLICT (name) DO NOTHING;

INSERT INTO events (name, type, team_size, icon, is_trial, season)
VALUES ('Optics', 'lab', 2, '🔭', true, '2025-2026')
ON CONFLICT (name) DO NOTHING;

INSERT INTO events (name, type, team_size, icon, is_trial, season)
VALUES ('Wind Power', 'build', 2, '💨', true, '2025-2026')
ON CONFLICT (name) DO NOTHING;


-- ─── 2. Insert questions (batched) ─────────────────────────────
-- True/False questions use: A=True, B=False, C='', D=''

-- ── Ecology (50 questions) ──
-- batch 1/5
INSERT INTO quiz_questions (event_id, topic, subtopic, question, options, correct_index, correct_answer_text, explanation, difficulty, question_type, points, source_tournament, ai_generated)
VALUES
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Metabolic Theory', NULL, 'The metabolic theory of ecology suggests that metabolic rates scale with body mass according to what exponent?', '["1.0", "-1.5", "-0.75", "0.25"]'::jsonb, 2, '-0.75', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Competition Models', NULL, 'In Lotka-Volterra competition models, what does a competition coefficient (α) greater than 1 indicate?', '["Intraspecific competition is stronger than interspecific competition", "Interspecific competition is stronger than intraspecific competition", "The populations are at equilibrium", "The species cannot coexist"]'::jsonb, 1, 'Interspecific competition is stronger than intraspecific competition', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Energy Flow', NULL, 'According to the Lindeman efficiency rule, approximately what percentage of energy is transferred between trophic levels?', '["50%", "10%", "25%", "1%"]'::jsonb, 1, '10%', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Survivorship Curves', NULL, 'Which of the following is a defining characteristic of a Type III survivorship curve?', '["High survival in early life stages, declining in later stages", "Constant mortality throughout life", "High mortality in early life, with survival increasing for older individuals", "Equal mortality across all age groups"]'::jsonb, 2, 'High mortality in early life, with survival increasing for older individuals', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Population Dynamics', NULL, 'The Allee effect describes:', '["A negative density dependence in population growth", "The impact of competition on carrying capacity", "The maximum reproductive potential of an organism", "A positive density dependence in population growth at low population sizes"]'::jsonb, 3, 'A positive density dependence in population growth at low population sizes', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Landscape Ecology', NULL, 'In the context of landscape ecology, what is meant by "percolation threshold"?', '["The maximum amount of habitat loss before species extinction occurs", "The point at which landscape connectivity allows for continuous species dispersal", "The rate at which water infiltrates soil in an ecosystem", "The temperature at which an ecosystem undergoes succession"]'::jsonb, 1, 'The point at which landscape connectivity allows for continuous species dispersal', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Photosynthesis', NULL, 'The C4 photosynthetic pathway is advantageous under which conditions?', '["High CO2 and low oxygen", "Low temperature and high moisture", "High temperature and low CO2", "High salinity and low nitrogen availability"]'::jsonb, 2, 'High temperature and low CO2', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Species-Area Relationship', NULL, 'Which of the following equations describes species-area relationships?', '["S = cA^z", "dN/dt = rN(1 - N/K)", "H'' = -\u03a3(pi ln pi)", "P = G + R"]'::jsonb, 0, 'S = cA^z', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Plant Ecology', NULL, 'The Janzen-Connell hypothesis suggests that:', '["Herbivory maintains plant diversity", "Seedling recruitment is suppressed near parent trees due to specialized predators", "Nutrient cycling efficiency increases with biodiversity", "Mycorrhizal associations drive forest succession"]'::jsonb, 1, 'Seedling recruitment is suppressed near parent trees due to specialized predators', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Aquatic Ecology', NULL, 'Which factor most influences primary productivity in freshwater lakes?', '["Phosphorus availability", "Iron deposition", "Wind speed", "Alkalinity"]'::jsonb, 0, 'Phosphorus availability', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false);

-- batch 2/5
INSERT INTO quiz_questions (event_id, topic, subtopic, question, options, correct_index, correct_answer_text, explanation, difficulty, question_type, points, source_tournament, ai_generated)
VALUES
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Ocean Chemistry', NULL, 'What is the primary mechanism by which increased atmospheric CO2 affects ocean acidity?', '["CO2 reacts with water to form carbonic acid", "CO2 blocks sunlight, reducing photosynthesis", "CO2 enhances biological calcification", "CO2 decreases the albedo effect"]'::jsonb, 0, 'CO2 reacts with water to form carbonic acid', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Ecosystem Services', NULL, 'The Millennium Ecosystem Assessment categorized ecosystem services into which four main types?', '["Supporting, provisioning, regulating, and cultural", "Nutrient cycling, photosynthesis, decomposition, and energy flow", "Carbon sequestration, biodiversity, water filtration, and soil formation", "Primary production, secondary production, trophic transfer, and respiration"]'::jsonb, 0, 'Supporting, provisioning, regulating, and cultural', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Biodiversity', NULL, 'What does a high beta diversity value indicate?', '["High species richness within a single site", "Low turnover of species across habitats", "High turnover of species between different habitats", "Even distribution of individuals within a community"]'::jsonb, 2, 'High turnover of species between different habitats', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Fisheries Management', NULL, 'In the context of fisheries, what does maximum sustainable yield (MSY) assume?', '["That fish populations do not interact with other species", "That populations grow logistically and have a fixed carrying capacity", "That harvesting does not impact reproductive success", "That marine reserves are unnecessary for conservation"]'::jsonb, 1, 'That populations grow logistically and have a fixed carrying capacity', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Biomes', NULL, 'Which biome is predicted to be most impacted by climate change in terms of biodiversity loss?', '["Tropical rainforests", "Boreal forests", "Temperate grasslands", "Deep-sea ecosystems"]'::jsonb, 2, 'Temperate grasslands', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Island Biogeography', NULL, 'What is the relationship between island size and species richness according to the theory of island biogeography?', '["Species richness decreases with increased island size", "Species richness increases with increased island size", "Island size has no impact on species richness", "Only proximity to the mainland influences species richness"]'::jsonb, 1, 'Species richness increases with increased island size', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Deep-Sea Ecosystems', NULL, 'Why do organisms living in deep-sea hydrothermal vents rely on chemosynthesis rather than photosynthesis?', '["Sunlight cannot penetrate to these depths", "There is an abundance of nutrients from surface runoff", "Deep-sea organisms lack photosynthetic pigments", "Photosynthesis is inefficient in saline environments"]'::jsonb, 0, 'Sunlight cannot penetrate to these depths', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Soil Ecology', NULL, 'What is the primary ecological role of earthworms in soil ecosystems?', '["Nitrogen fixation", "Decomposition and nutrient cycling", "Pollination", "Carbon sequestration"]'::jsonb, 1, 'Decomposition and nutrient cycling', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Diversity Indices', NULL, 'How does the Simpson Index differ from the Shannon-Wiener Index?', '["The Simpson Index emphasizes species richness over evenness", "The Shannon-Wiener Index ignores species evenness", "The Simpson Index measures only the number of species in a community", "The Shannon-Wiener Index accounts for rare species more than the Simpson Index"]'::jsonb, 3, 'The Shannon-Wiener Index accounts for rare species more than the Simpson Index', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Niche Theory', NULL, 'What is the key difference between fundamental and realized niches?', '["The fundamental niche accounts for competition, while the realized niche does not", "The realized niche is the actual space an organism inhabits due to interactions with other species", "Fundamental niches are determined by biotic factors, while realized niches are purely abiotic", "Realized niches exist only in disturbed ecosystems"]'::jsonb, 1, 'The realized niche is the actual space an organism inhabits due to interactions with other species', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false);

-- batch 3/5
INSERT INTO quiz_questions (event_id, topic, subtopic, question, options, correct_index, correct_answer_text, explanation, difficulty, question_type, points, source_tournament, ai_generated)
VALUES
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Grassland Ecology', NULL, 'Which soil type is most characteristic of temperate grasslands?', '["Spodosol", "Histosol", "Mollisol", "Oxisol"]'::jsonb, 2, 'Mollisol', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Grassland Ecology', NULL, 'What primary factor limits tree growth in grasslands?', '["Low precipitation", "High herbivore diversity", "Poor soil aeration", "High nitrogen availability"]'::jsonb, 0, 'Low precipitation', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Grassland Ecology', NULL, 'C4 grasses have an advantage over C3 grasses in:', '["Cold, wet environments", "High temperature, low CO2 environments", "Nutrient-rich, shaded forests", "High-latitude tundra regions"]'::jsonb, 1, 'High temperature, low CO2 environments', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Grassland Ecology', NULL, 'Fire plays a critical role in grassland ecology because it:', '["Reduces nitrogen availability", "Encourages woody plant succession", "Maintains open landscapes by preventing tree encroachment", "Increases soil alkalinity"]'::jsonb, 2, 'Maintains open landscapes by preventing tree encroachment', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Grassland Ecology', NULL, 'The dominant grassland biome in North America is the:', '["Pampas", "Steppe", "Prairie", "Veld"]'::jsonb, 2, 'Prairie', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Grassland Ecosystems', NULL, 'Which of the following grassland regions is maintained by seasonal flooding?', '["Serengeti", "Everglades", "Llanos", "Great Plains"]'::jsonb, 2, 'Llanos', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Grassland Ecology', NULL, 'How do grasses primarily adapt to grazing pressure?', '["By producing secondary metabolites that deter herbivory", "By developing deep root systems for water access", "By growing from basal meristems rather than apical buds", "By increasing leaf thickness to minimize water loss"]'::jsonb, 2, 'By growing from basal meristems rather than apical buds', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Grassland Ecology', NULL, 'What is the primary mechanism driving species diversity in grasslands?', '["High annual precipitation", "Frequent disturbance events such as grazing and fire", "High soil nutrient levels", "Strong interspecies competition"]'::jsonb, 1, 'Frequent disturbance events such as grazing and fire', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Grassland Ecosystems', NULL, 'The Serengeti ecosystem is famous for its large-scale migration of which herbivore?', '["American bison", "Gazelle", "Przewalski''s horse", "Wildebeest"]'::jsonb, 3, 'Wildebeest', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Grassland Degradation', NULL, 'Which of the following factors is a major contributor to grassland desertification?', '["Increased native herbivore populations", "Overgrazing by livestock", "Expansion of wetlands", "Increased CO2 fertilization"]'::jsonb, 1, 'Overgrazing by livestock', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false);

-- batch 4/5
INSERT INTO quiz_questions (event_id, topic, subtopic, question, options, correct_index, correct_answer_text, explanation, difficulty, question_type, points, source_tournament, ai_generated)
VALUES
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Grassland Ecosystems', NULL, 'The primary difference between tallgrass and shortgrass prairie ecosystems is:', '["Soil nitrogen availability", "Fire frequency", "Annual precipitation levels", "Presence of large herbivores"]'::jsonb, 2, 'Annual precipitation levels', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Grassland Ecology', NULL, 'What role do mycorrhizal fungi play in grassland ecosystems?', '["They fix atmospheric nitrogen", "They enhance phosphorus uptake in plant roots", "They increase soil compaction", "They promote insect pollination"]'::jsonb, 1, 'They enhance phosphorus uptake in plant roots', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Grassland Ecology', NULL, 'What is the primary adaptation that allows grasses to survive extended droughts?', '["The ability to store water in above-ground stems", "Aerenchyma tissue development", "Extensive below-ground root systems", "High transpiration rates"]'::jsonb, 2, 'Extensive below-ground root systems', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Grassland Ecology', NULL, 'Which of the following processes is most responsible for the maintenance of grassland biodiversity?', '["Primary succession", "Fire suppression", "Periodic grazing and fire disturbance", "Increased CO2 concentration in the atmosphere"]'::jsonb, 2, 'Periodic grazing and fire disturbance', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Carbon Cycling', NULL, 'Grasslands contribute significantly to global carbon cycles through:', '["Carbon fixation by fast-growing woody plants", "The deep sequestration of organic material in soils", "Increased methane emissions from herbivores", "Rapid decomposition of above-ground biomass"]'::jsonb, 1, 'The deep sequestration of organic material in soils', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Grassland Ecology', NULL, 'Which of the following best explains why beta diversity is often higher in grassland ecosystems compared to forests?', '["Grasslands experience more frequent disturbances, leading to increased species turnover.", "Forests have higher species richness, which results in higher beta diversity.", "Grassland species are highly specialized, leading to low overlap between different locations.", "Grasslands have fewer primary producers, reducing competitive exclusion and increasing diversity."]'::jsonb, 0, 'Grasslands experience more frequent disturbances, leading to increased species turnover.', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Diversity Indices', NULL, 'The Shannon-Wiener Index (H'') is commonly used to measure biodiversity. If a grassland ecosystem has an H'' value close to zero, what does this indicate?', '["High species evenness but low richness", "A dominance of a single species with very low diversity", "A perfectly even distribution of species", "High richness but low evenness"]'::jsonb, 1, 'A dominance of a single species with very low diversity', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Grassland Ecology', NULL, 'Which of the following processes contributes the most to functional redundancy in grassland biodiversity?', '["Low genetic variation within individual species populations", "Strong interspecific competition leading to niche differentiation", "Frequent herbivory reducing plant species dominance", "High niche overlap among plant species"]'::jsonb, 3, 'High niche overlap among plant species', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Species-Area Relationship', NULL, 'According to the species-area relationship (S = cA^z), what is the most likely consequence of habitat fragmentation in a temperate grassland ecosystem?', '["Loss of specialist species due to reduced available habitat", "Increase in ecosystem stability due to reduced species interactions", "Increased species richness as smaller patches provide unique microhabitats", "Lower extinction rates due to decreased competition for resources"]'::jsonb, 0, 'Loss of specialist species due to reduced available habitat', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Grassland Conservation', NULL, 'In the context of grassland biodiversity conservation, why is the introduction of non-native C4 grasses often problematic?', '["Non-native grasses increase nitrogen fixation, altering soil nutrient cycling.", "They outcompete native C3 grasses, reducing plant species diversity and ecosystem function.", "They increase CO2 sequestration, leading to changes in microbial diversity.", "Non-native grasses provide less food for herbivores, leading to trophic cascades."]'::jsonb, 1, 'They outcompete native C3 grasses, reducing plant species diversity and ecosystem function.', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false);

-- batch 5/5
INSERT INTO quiz_questions (event_id, topic, subtopic, question, options, correct_index, correct_answer_text, explanation, difficulty, question_type, points, source_tournament, ai_generated)
VALUES
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Habitat Fragmentation', NULL, 'Which of the following is the primary cause of habitat fragmentation in temperate grasslands?', '["Fire suppression policies", "Conversion to agricultural land", "Increased precipitation due to climate change", "Decline in herbivore populations"]'::jsonb, 1, 'Conversion to agricultural land', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Habitat Fragmentation', NULL, 'The "edge effect" resulting from habitat fragmentation typically leads to:', '["Increased genetic diversity in isolated populations", "Higher rates of predation and invasive species establishment", "Greater ecosystem stability and resilience", "Increased primary productivity in interior habitat zones"]'::jsonb, 1, 'Higher rates of predation and invasive species establishment', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Grassland Restoration', NULL, 'Which soil remediation technique is most effective in restoring nutrient-depleted grasslands?', '["Introduction of nitrogen-fixing plant species", "Clear-cutting of invasive woody vegetation", "Deep plowing to increase soil aeration", "Artificial wetland construction"]'::jsonb, 0, 'Introduction of nitrogen-fixing plant species', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Ecosystem Restoration', NULL, 'The introduction of keystone species into a disturbed ecosystem is an example of:', '["Passive restoration", "Ecological engineering", "Assisted migration", "Trophic rewilding"]'::jsonb, 3, 'Trophic rewilding', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Ecosystem Restoration', NULL, 'Which of the following best describes the goal of reconciliation ecology in habitat restoration?', '["Removing all human influence to restore historical ecosystem conditions", "Designing urban spaces and agricultural landscapes to support biodiversity", "Establishing strict no-use conservation zones to minimize human disturbance", "Utilizing genetically modified species to enhance ecosystem function"]'::jsonb, 1, 'Designing urban spaces and agricultural landscapes to support biodiversity', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Desertification Management', NULL, 'In response to desertification, a commonly implemented mitigation strategy involves:', '["Applying synthetic fertilizers to increase soil fertility", "Constructing windbreaks to reduce erosion and water loss", "Removing all vegetation to prevent further degradation", "Increasing groundwater extraction to support plant growth"]'::jsonb, 1, 'Constructing windbreaks to reduce erosion and water loss', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Habitat Degradation', NULL, 'Which factor contributes the most to "biotic homogenization" in degraded habitats?', '["Increased local adaptation of native species", "Expansion of invasive generalist species replacing specialists", "Reduced nutrient cycling due to lower decomposition rates", "Restoration of primary producer communities through seeding"]'::jsonb, 1, 'Expansion of invasive generalist species replacing specialists', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Restoration Techniques', NULL, 'What is the primary disadvantage of seed banks as a habitat restoration tool?', '["They reduce the genetic variability of wild plant populations", "They only store seeds of commercially valuable species", "Seeds may not germinate effectively in degraded soil conditions", "They accelerate genetic drift in natural populations"]'::jsonb, 2, 'Seeds may not germinate effectively in degraded soil conditions', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Grassland Restoration', NULL, 'Why is prescribed burning an effective restoration tool for some grassland ecosystems?', '["It increases water retention in the soil", "It removes invasive species while promoting fire-adapted native plants", "It enhances the carbon sequestration potential of the ecosystem", "It increases soil compaction, preventing erosion"]'::jsonb, 1, 'It removes invasive species while promoting fire-adapted native plants', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Restoration Techniques', NULL, 'Which of the following is a major challenge in using bioaugmentation for habitat restoration?', '["Difficulty in selecting appropriate microbial species", "Lack of available nutrients in restored soils", "High costs associated with implementing the technique", "Ineffectiveness in non-wetland ecosystems"]'::jsonb, 0, 'Difficulty in selecting appropriate microbial species', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false);

-- ── Meteorology (20 questions) ──
-- batch 1/2
INSERT INTO quiz_questions (event_id, topic, subtopic, question, options, correct_index, correct_answer_text, explanation, difficulty, question_type, points, source_tournament, ai_generated)
VALUES
  ((SELECT id FROM events WHERE name = 'Meteorology'), 'Radiation and Albedo', NULL, 'Albedo is the amount of light absorbed by a surface, such as the Earth.', '["True", "False", "", ""]'::jsonb, 1, 'False', NULL, 'easy', 'true_false', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Meteorology'), 'Solar Radiation', NULL, 'The equator is warmer than the poles because there is more incoming solar radiation where the Earth''s shape bulges.', '["True", "False", "", ""]'::jsonb, 0, 'True', NULL, 'medium', 'true_false', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Meteorology'), 'Earth''s Surface', NULL, '70% of the earth''s surface is covered by ocean.', '["True", "False", "", ""]'::jsonb, 0, 'True', NULL, 'easy', 'true_false', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Meteorology'), 'Heat Capacity', NULL, 'Land absorbs and maintains heat better than the ocean.', '["True", "False", "", ""]'::jsonb, 1, 'False', NULL, 'medium', 'true_false', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Meteorology'), 'Ocean Oscillations', NULL, 'El Nino and La Nina are cold and warm phases in the Pacific Ocean.', '["True", "False", "", ""]'::jsonb, 0, 'True', NULL, 'medium', 'true_false', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Meteorology'), 'Climate and Weather', NULL, 'Climate is a specific event that happens over a short period and weather is the average weather conditions over a long period of time.', '["True", "False", "", ""]'::jsonb, 1, 'False', NULL, 'easy', 'true_false', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Meteorology'), 'Greenhouse Effect', NULL, 'Excess greenhouse gases in the atmosphere are the main reason global temperatures are increasing.', '["True", "False", "", ""]'::jsonb, 0, 'True', NULL, 'easy', 'true_false', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Meteorology'), 'Ocean and Coral', NULL, 'Increased ocean temperatures do not affect coral reefs in the ocean.', '["True", "False", "", ""]'::jsonb, 1, 'False', NULL, 'easy', 'true_false', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Meteorology'), 'Atmospheric Circulation', NULL, 'The Intertropical Convergence Zone (ITCZ) is caused by low pressure from intense solar heating over the equator.', '["True", "False", "", ""]'::jsonb, 0, 'True', NULL, 'medium', 'true_false', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Meteorology'), 'Atmospheric Layers', NULL, 'Which layer of the atmosphere contains the most ozone?', '["Troposphere", "Stratosphere", "Thermosphere", "Mesosphere"]'::jsonb, 1, 'Stratosphere', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false);

-- batch 2/2
INSERT INTO quiz_questions (event_id, topic, subtopic, question, options, correct_index, correct_answer_text, explanation, difficulty, question_type, points, source_tournament, ai_generated)
VALUES
  ((SELECT id FROM events WHERE name = 'Meteorology'), 'Greenhouse Gases', NULL, 'What is the primary greenhouse gas in Earth''s atmosphere?', '["Methane (CH4)", "Fluorinated gases", "Carbon Dioxide (CO2)", "Nitrous Oxide (N2O)"]'::jsonb, 2, 'Carbon Dioxide (CO2)', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Meteorology'), 'Feedback Loops', NULL, 'Which of the following is true when there is ice-albedo feedback? (Select all that apply)', '["Temperatures warm and ice starts to melt", "Albedo of Earth decreases", "Further warming occurs", "All the above"]'::jsonb, 3, 'All the above', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Meteorology'), 'Climate Change', NULL, 'During the last ice age, atmospheric CO2 and CH4 concentrations were lower looking at air trapped in ice cores. What trend in CO2 would we see since the last ice age considering our current climate and future climate projections?', '["Continuous decreases in CO2 concentrations", "Aggressive increase in CO2 concentrations", "CO2 concentrations would remain the same", "None of the above"]'::jsonb, 1, 'Aggressive increase in CO2 concentrations', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Meteorology'), 'Ocean Energy', NULL, 'The ocean is the largest solar energy collector on Earth, while also collecting longwave radiation from the Earth''s surface that can''t escape to space. What impact does this collection of radiation have on the ocean temperatures?', '["Temperatures stay the same", "Temperature decrease", "Temperatures increase", "None of the above"]'::jsonb, 2, 'Temperatures increase', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Meteorology'), 'Climate Data', NULL, 'What is the minimum time interval used for data to be considered "climatic data"?', '["30 years", "50 years", "100 years", "10 years"]'::jsonb, 0, '30 years', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Meteorology'), 'Solar Radiation Variation', NULL, 'What climatic region experiences the largest variation in daylight throughout the year due to the Earth''s tilt?', '["Polar regions", "Deserts", "Rainforests", "Tropical islands"]'::jsonb, 0, 'Polar regions', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Meteorology'), 'Meteorology Scales', NULL, 'Which of the following is NOT a temporal or spatial scale of meteorology?', '["Synoptic", "Tropical", "Microscale", "Mesoscale"]'::jsonb, 1, 'Tropical', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Meteorology'), 'Ocean Currents', NULL, 'Ocean gyres are large systems of circular currents in the ocean. Which two factors influence their formation?', '["Global wind patterns and Low pressure systems", "Temperature gradients and Forces created by Earth''s rotation", "Forces created by Earth''s rotation", "Global wind patterns"]'::jsonb, 3, 'Global wind patterns and Forces created by Earth''s rotation', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Meteorology'), 'Climate Sensitivity', NULL, 'Climate sensitivity is often expressed in units of _________.', '["\u00b0C/W", "\u00b0C/J", "\u00b0C/(W/m\u00b2)", "\u00b0C/(W/m)"]'::jsonb, 2, '°C/(W/m²)', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Meteorology'), 'Sea Level', NULL, 'Which of the following can result from a global rise or fall in sea level?', '["Local variations in ocean temperature", "Melting ice sheets", "Extreme rainfall from tropical cyclones", "A change in ocean density"]'::jsonb, 1, 'Melting ice sheets', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false);

-- ── Optics (12 questions) ──
-- batch 1/2
INSERT INTO quiz_questions (event_id, topic, subtopic, question, options, correct_index, correct_answer_text, explanation, difficulty, question_type, points, source_tournament, ai_generated)
VALUES
  ((SELECT id FROM events WHERE name = 'Optics'), 'Light and Color', NULL, 'Which of the following best explains why the sky appears blue?', '["The atmosphere preferentially scatters shorter wavelengths of light", "The ocean reflects blue light into the sky", "Air molecules absorb red light and emit blue light", "The human eye is more sensitive to blue than red in daylight"]'::jsonb, 0, 'The atmosphere preferentially scatters shorter wavelengths of light', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Optics'), 'Reflection', NULL, 'Which of the following is NOT an example of specular reflection?', '["Light reflecting off a calm lake", "Light reflecting off a polished metal surface", "Light reflecting off a white sheet of paper", "Light reflecting off a smooth glass window"]'::jsonb, 2, 'Light reflecting off a white sheet of paper', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Optics'), 'Mirrors', NULL, 'Why can you always see your full body in a mirror that is only half your height?', '["The mirror bends light to make you look smaller", "The mirror magnifies the image", "Light reflects symmetrically, so only half is needed to capture your full reflection", "The brain adjusts the image automatically"]'::jsonb, 2, 'Light reflects symmetrically, so only half is needed to capture your full reflection', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Optics'), 'Color and Light', NULL, 'Why does a red apple appear red under white light?', '["It absorbs red light and reflects all other colors", "It reflects red light and absorbs all other colors", "It absorbs blue and green light but reflects red light", "It emits red light on its own"]'::jsonb, 2, 'It absorbs blue and green light but reflects red light', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Optics'), 'Color and Light', NULL, 'Which of the following statements is TRUE about the primary colors of light?', '["Mixing red and blue light creates yellow", "The primary colors of light are red, blue, and green", "The primary colors of light are the same as pigment colors", "White light is made by mixing cyan, magenta, and yellow"]'::jsonb, 1, 'The primary colors of light are red, blue, and green', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Optics'), 'Color and Light', NULL, 'What color will a yellow object appear if illuminated by pure blue light?', '["Yellow", "Green", "Black", "White"]'::jsonb, 2, 'Black', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Optics'), 'Eye Anatomy', NULL, 'Which part of the eye controls the amount of light entering the pupil?', '["Cornea", "Lens", "Iris", "Retina"]'::jsonb, 2, 'Iris', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Optics'), 'Eye Conditions', NULL, 'Which of the following conditions is caused by the eyeball being too long, causing distant objects to appear blurry?', '["Hyperopia (Farsightedness)", "Myopia (Nearsightedness)", "Astigmatism", "Presbyopia"]'::jsonb, 1, 'Myopia (Nearsightedness)', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Optics'), 'Eye Conditions', NULL, 'A person with astigmatism has difficulty seeing clearly because:', '["Their eye lens is too rigid", "Their cornea or lens is irregularly shaped", "Their retina is damaged", "Their optic nerve is underdeveloped"]'::jsonb, 1, 'Their cornea or lens is irregularly shaped', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Optics'), 'Mirrors', NULL, 'What type of image does a plane mirror always produce?', '["Real and inverted", "Real and upright", "Virtual and inverted", "Virtual and upright"]'::jsonb, 3, 'Virtual and upright', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false);

-- batch 2/2
INSERT INTO quiz_questions (event_id, topic, subtopic, question, options, correct_index, correct_answer_text, explanation, difficulty, question_type, points, source_tournament, ai_generated)
VALUES
  ((SELECT id FROM events WHERE name = 'Optics'), 'Mirrors', NULL, 'You are standing in front of the mirror and see your image. Now you take two steps towards your image. How does the distance between you and your image change?', '["4 steps closer", "4 steps away", "Same distance", "2 steps closer"]'::jsonb, 0, '4 steps closer', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Optics'), 'Mirrors', NULL, 'You are in a room with mirrored walls, floor, and ceiling. How many images of yourself can you see?', '["One", "Two", "A few dozen", "An infinite number"]'::jsonb, 3, 'An infinite number', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false);

-- ── Reach for the Stars (24 questions) ──
-- batch 1/3
INSERT INTO quiz_questions (event_id, topic, subtopic, question, options, correct_index, correct_answer_text, explanation, difficulty, question_type, points, source_tournament, ai_generated)
VALUES
  ((SELECT id FROM events WHERE name = 'Reach for the Stars'), 'Stellar Classification', NULL, 'If stars A and B have the same luminosity, star A is twice as far away from Earth as star B, and the light coming from star A experiences the same amount of extinction as star B, the absolute magnitudes of the two stars are the same.', '["True", "False", "", ""]'::jsonb, 0, 'True', NULL, 'hard', 'true_false', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Reach for the Stars'), 'Stellar Classification', NULL, 'If the absolute magnitudes of two stars differ by 1.0, and they are the same distance to earth, then it means their absolute magnitudes must also differ by 1.0.', '["True", "False", "", ""]'::jsonb, 0, 'True', NULL, 'medium', 'true_false', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Reach for the Stars'), 'Binary Systems', NULL, 'The accretor of an X-ray binary system is usually a white dwarf.', '["True", "False", "", ""]'::jsonb, 0, 'True', NULL, 'medium', 'true_false', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Reach for the Stars'), 'Stellar Evolution', NULL, 'Stars with an initial mass around 0.7 M are generally unable to undergo a core helium flash.', '["True", "False", "", ""]'::jsonb, 0, 'True', NULL, 'hard', 'true_false', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Reach for the Stars'), 'Stellar Evolution', NULL, 'Stars with an initial mass around 7 M generally end their life in a core collapse supernova.', '["True", "False", "", ""]'::jsonb, 0, 'True', NULL, 'hard', 'true_false', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Reach for the Stars'), 'Stellar Classification', NULL, 'Class B stars have a higher surface temperature than class A stars.', '["True", "False", "", ""]'::jsonb, 1, 'False', NULL, 'easy', 'true_false', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Reach for the Stars'), 'Stellar Classification', NULL, 'Class F stars have a higher surface temperature than class G stars.', '["True", "False", "", ""]'::jsonb, 0, 'True', NULL, 'easy', 'true_false', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Reach for the Stars'), 'White Dwarfs', NULL, 'White dwarfs with larger radii are denser than white dwarfs with smaller radii.', '["True", "False", "", ""]'::jsonb, 1, 'False', NULL, 'hard', 'true_false', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Reach for the Stars'), 'Stellar Evolution', NULL, 'Only stars that are type O on the main sequence are massive enough to undergo core collapse supernovae.', '["True", "False", "", ""]'::jsonb, 1, 'False', NULL, 'hard', 'true_false', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Reach for the Stars'), 'Stellar Classification', NULL, 'A main sequence star with a mass of around 3 M belongs in spectral class A.', '["True", "False", "", ""]'::jsonb, 1, 'False', NULL, 'medium', 'true_false', 1, 'Badger Invitational 2025', false);

-- batch 2/3
INSERT INTO quiz_questions (event_id, topic, subtopic, question, options, correct_index, correct_answer_text, explanation, difficulty, question_type, points, source_tournament, ai_generated)
VALUES
  ((SELECT id FROM events WHERE name = 'Reach for the Stars'), 'Stellar Evolution', NULL, 'All stars above 8 M end their life with a supernova.', '["True", "False", "", ""]'::jsonb, 0, 'True', NULL, 'hard', 'true_false', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Reach for the Stars'), 'Stellar Evolution', NULL, 'What event marks the start of the planetary nebula stage of a low to intermediate mass star''s life?', '["Start of ejecta ionization by star''s core", "End of core nuclear fusion", "End of shell nuclear fusion", "Start of large-scale mass loss in stellar envelope"]'::jsonb, 0, 'Start of ejecta ionization by star''s core', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Reach for the Stars'), 'White Dwarfs', NULL, 'Which physical phenomenon is most directly responsible for the electron degeneracy pressure that keeps white dwarfs from further collapse?', '["Strong nuclear force", "Electromagnetism", "Pauli exclusion principle", "Gravity"]'::jsonb, 2, 'Pauli exclusion principle', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Reach for the Stars'), 'White Dwarfs', NULL, 'Above what approximate mass is electron degeneracy pressure unable to stop a star''s core or a white dwarf from collapsing further?', '["1.18 M", "1.44 M", "1.62 M", "2.06 M"]'::jsonb, 1, '1.44 M', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Reach for the Stars'), 'White Dwarfs', NULL, 'Which two elements account for the largest portion of a white dwarf''s mass, given the progenitor star was of spectral type G during the main sequence?', '["Fe and Ni", "Si and Ne", "H and He", "C and O"]'::jsonb, 3, 'C and O', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Reach for the Stars'), 'Stellar Evolution', NULL, 'Which stage of stellar evolution begins when a low mass star begins helium fusion in its core?', '["Subgiant Branch", "Red Giant Branch", "Horizontal Branch", "Asymptotic Giant Branch"]'::jsonb, 2, 'Horizontal Branch', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Reach for the Stars'), 'Variable Stars', NULL, 'At the stage mentioned in the previous question, the stars can be further split on the HR-diagram into a red branch and a blue branch, separated by a gap on the instability strip. Which class of variable stars lies in this gap?', '["RR Lyrae variables", "Classic Cepheid variables", "Mira variables", "Wolf Rayet stars"]'::jsonb, 0, 'RR Lyrae variables', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Reach for the Stars'), 'Stellar Evolution', NULL, 'What mechanism is most directly responsible for the expansion in the outer envelope of a low mass star after core hydrogen fusion stops and before core helium fusion starts?', '["Coronal mass ejection", "Shell hydrogen fusion", "Core lithium fusion", "Stellar convection"]'::jsonb, 1, 'Shell hydrogen fusion', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Reach for the Stars'), 'Supernovae', NULL, 'What emissions spectral feature separates Type I and Type II supernovae?', '["Lack of any Hydrogen lines", "Presence Calcium II lines", "Lack of any Helium lines", "Presence of Oxygen lines"]'::jsonb, 0, 'Lack of any Hydrogen lines', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Reach for the Stars'), 'Supernovae', NULL, 'Which class of Type I supernova is the result of white dwarf accretion or white dwarfs merging, as opposed to stellar core collapse?', '["Type Ia", "Type Ib", "Type Ic", "Type Ipec"]'::jsonb, 0, 'Type Ia', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false);

-- batch 3/3
INSERT INTO quiz_questions (event_id, topic, subtopic, question, options, correct_index, correct_answer_text, explanation, difficulty, question_type, points, source_tournament, ai_generated)
VALUES
  ((SELECT id FROM events WHERE name = 'Reach for the Stars'), 'Binary Systems', NULL, 'In what type of star system is this type of supernova most likely to occur?', '["Single star systems with many gaseous planets", "Binary star systems with massive stars", "Binary star systems with low mass stars", "Binary star systems with a black hole"]'::jsonb, 2, 'Binary star systems with low mass stars', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Reach for the Stars'), 'Binary Systems', NULL, 'How does the frequency and intensity of dwarf novae compare to classical novae?', '["Dwarf novae are less intense and more frequent", "Dwarf novae are less intense and less frequent", "Dwarf novae are more intense and less frequent", "Dwarf novae are more intense and more frequent"]'::jsonb, 0, 'Dwarf novae are less intense and more frequent', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Reach for the Stars'), 'Binary Systems', NULL, 'Which type of X-ray binary system usually has a white dwarf as the accretor instead of a neutron star or black hole', '["Soft X-ray transients", "Low mass X-ray binary", "Intermediate mass X-ray binary", "Supersoft X-ray source"]'::jsonb, 3, 'Supersoft X-ray source', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Reach for the Stars'), 'Stellar Evolution', NULL, 'Which stage of stellar evolution begins when a low to intermediate mass star exhausts both the supply of hydrogen and helium in its core, being left with an inert core of carbon and oxygen?', '["Subgiant Branch", "Red Giant Branch", "Horizontal Branch", "Asymptotic Giant Branch"]'::jsonb, 3, 'Asymptotic Giant Branch', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false);

-- ── Wind Power (30 questions) ──
-- batch 1/3
INSERT INTO quiz_questions (event_id, topic, subtopic, question, options, correct_index, correct_answer_text, explanation, difficulty, question_type, points, source_tournament, ai_generated)
VALUES
  ((SELECT id FROM events WHERE name = 'Wind Power'), 'Blade Design', NULL, 'What is the main function of the pitch system in a wind turbine?', '["Converting wind energy into mechanical energy", "Adjusting blade angles for optimal rotor speed", "Supporting the main shaft", "Stopping the rotor in emergency situations"]'::jsonb, 1, 'Adjusting blade angles for optimal rotor speed', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Wind Power'), 'Blade Design', NULL, 'What does the yaw system do in a wind turbine?', '["Changes the angle of attack", "Rotates the nacelle to align with wind direction", "Stops the rotor during maintenance", "Controls electricity output"]'::jsonb, 1, 'Rotates the nacelle to align with wind direction', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Wind Power'), 'Energy Conversion', NULL, 'What principle explains how wind turbine blades generate lift?', '["Pascal''s Principle", "Bernoulli''s Principle", "Newton''s First Law", "Archimedes'' Principle"]'::jsonb, 1, 'Bernoulli''s Principle', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Wind Power'), 'Blade Design', NULL, 'Why are wind turbine blades twisted?', '["To reduce material cost", "To allow each section of the blade to have an optimal angle of attack", "To decrease rotor speed", "To prevent structural damage"]'::jsonb, 1, 'To allow each section of the blade to have an optimal angle of attack', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Wind Power'), 'Blade Design', NULL, 'What is the optimal strategy for regulating turbine rotational speed in high wind conditions?', '["Increase the angle of attack", "Active stall control", "Decrease the blade twist", "Increase the number of blades"]'::jsonb, 1, 'Active stall control', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Wind Power'), 'Energy Conversion', NULL, 'What is the primary use of a transformer?', '["To increase resistance", "To store electrical energy", "To change the voltage level in an AC circuit", "To block DC currents"]'::jsonb, 2, 'To change the voltage level in an AC circuit', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Wind Power'), 'Electrical Systems', NULL, 'What happens to the current in a purely resistive AC circuit?', '["It leads voltage by 90 degrees", "It lags behind voltage by 90 degrees", "It is in phase with the voltage", "There is no current flow"]'::jsonb, 2, 'It is in phase with the voltage', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Wind Power'), 'Electrical Systems', NULL, 'Which of the following devices stores energy in a magnetic field?', '["Resistor", "Capacitor", "Inductor", "Transformer"]'::jsonb, 2, 'Inductor', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Wind Power'), 'Electrical Systems', NULL, 'Active power in an AC circuit is measured in:', '["VA (Volt-Amperes)", "Watts", "Ohms", "Farads"]'::jsonb, 1, 'Watts', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Wind Power'), 'Electrical Systems', NULL, 'The unit of capacitance is:', '["Ohms", "Farads", "Henrys", "Joules"]'::jsonb, 1, 'Farads', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false);

-- batch 2/3
INSERT INTO quiz_questions (event_id, topic, subtopic, question, options, correct_index, correct_answer_text, explanation, difficulty, question_type, points, source_tournament, ai_generated)
VALUES
  ((SELECT id FROM events WHERE name = 'Wind Power'), 'Electrical Systems', NULL, 'A device that resists changes in current flow is called a(n):', '["Resistor", "Inductor", "Capacitor", "Battery"]'::jsonb, 1, 'Inductor', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Wind Power'), 'Electrical Systems', NULL, 'The formula P = V × I × cosφ represents:', '["Reactive power", "Active power", "Apparent power", "Magnetic field strength"]'::jsonb, 1, 'Active power', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Wind Power'), 'Energy Storage', NULL, 'What is the primary reason energy storage is needed for wind and solar power?', '["To reduce energy costs", "To provide backup power during low production times", "To eliminate the need for batteries", "To increase fossil fuel usage"]'::jsonb, 1, 'To provide backup power during low production times', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Wind Power'), 'Energy Conversion', NULL, 'What type of solar cell is most efficient?', '["Polycrystalline silicon", "Monocrystalline silicon", "Amorphous silicon", "Cadmium telluride"]'::jsonb, 1, 'Monocrystalline silicon', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Wind Power'), 'Energy Storage', NULL, 'What is the primary function of the electrolyte in a battery?', '["To store energy", "To allow ion movement between electrodes", "To prevent electricity flow", "To increase the reliability of the battery"]'::jsonb, 1, 'To allow ion movement between electrodes', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Wind Power'), 'Energy Conversion', NULL, 'Which energy source does a concentrated solar power plant use?', '["Photovoltaic panels", "Molten salt storage", "Fossil fuels", "Geothermal heat"]'::jsonb, 1, 'Molten salt storage', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Wind Power'), 'Energy Conversion', NULL, 'What is the purpose of control rods in a nuclear reactor?', '["To increase temperature", "To speed up nuclear fission", "To regulate the reaction and absorb excess neutrons", "To store nuclear waste"]'::jsonb, 2, 'To regulate the reaction and absorb excess neutrons', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Wind Power'), 'Electrical Systems', NULL, 'What is the primary function of power electronics?', '["To generate electricity", "To convert and control electrical power for various applications", "To transmit mechanical energy", "To store electrical energy in batteries"]'::jsonb, 1, 'To convert and control electrical power for various applications', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Wind Power'), 'Electrical Systems', NULL, 'Which component in power electronics acts as a switch that can rapidly turn on and off?', '["Capacitor", "Inductor", "Power Semiconductor", "Transformer"]'::jsonb, 2, 'Power Semiconductor', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Wind Power'), 'Energy Conversion', NULL, 'Which type of converter is used to convert DC power into AC power?', '["Rectifier", "Chopper", "Inverter", "Transformer"]'::jsonb, 2, 'Inverter', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false);

-- batch 3/3
INSERT INTO quiz_questions (event_id, topic, subtopic, question, options, correct_index, correct_answer_text, explanation, difficulty, question_type, points, source_tournament, ai_generated)
VALUES
  ((SELECT id FROM events WHERE name = 'Wind Power'), 'Energy Conversion', NULL, 'What is the primary purpose of a rectifier?', '["To convert AC to DC", "To store electrical energy", "To step up voltage", "To convert DC to AC"]'::jsonb, 0, 'To convert AC to DC', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Wind Power'), 'Electrical Systems', NULL, 'What role do wind turbine inverters play in grid synchronization?', '["They increase the speed of wind turbines", "They match the voltage, frequency, and phase with the grid", "They generate additional power from fossil fuels", "They store excess power in batteries"]'::jsonb, 1, 'They match the voltage, frequency, and phase with the grid', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Wind Power'), 'Energy Storage', NULL, 'What is the primary difference between a supercapacitor and a traditional capacitor?', '["Supercapacitors store energy chemically, while traditional capacitors store it electrostatically", "Supercapacitors have a dielectric material, while traditional capacitors do not", "Supercapacitors store energy electrostatically with an electrolyte, allowing higher energy density", "Traditional capacitors have higher energy density than supercapacitors"]'::jsonb, 2, 'Supercapacitors store energy electrostatically with an electrolyte, allowing higher energy density', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Wind Power'), 'Energy Conversion', NULL, 'Why do superconductors exhibit zero electrical resistance?', '["Electrons move faster at low temperatures", "Electrons form Cooper pairs, allowing resistance-free movement", "Superconductors have a special insulation layer", "Magnetic fields inside superconductors generate current without resistance"]'::jsonb, 1, 'Electrons form Cooper pairs, allowing resistance-free movement', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Wind Power'), 'Energy Conversion', NULL, 'What is a key advantage of high-temperature superconductors (HTS) over traditional superconductors?', '["They do not require cooling", "They can operate above the boiling point of liquid nitrogen", "They are cheaper to manufacture than copper wires", "They can be used at room temperature"]'::jsonb, 1, 'They can operate above the boiling point of liquid nitrogen', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Wind Power'), 'Energy Sources', NULL, 'Which renewable energy source has the lowest GHG emissions?', '["Hydropower", "Solar PV", "Wind power", "Geothermal"]'::jsonb, 2, 'Wind power', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Wind Power'), 'Climate Change', NULL, 'What is the primary mechanism by which CO2 emissions contribute to climate change?', '["Ice core samples contain fossilized plants", "Ice core samples show constant CO2 levels over time", "CO2 levels in ice cores correlate with temperature changes over glacial cycles", "Ice core samples have no relation to CO2 measurements"]'::jsonb, 2, 'CO2 levels in ice cores correlate with temperature changes over glacial cycles', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Wind Power'), 'Climate Change', NULL, 'How does a small temperature increase (e.g. 1.2°C) affect global ecosystems?', '["It has no significant effects", "It causes widespread changes, including habitat loss and shifting weather patterns", "It only affects regions near the equator", "It improves conditions for all plant life"]'::jsonb, 1, 'It causes widespread changes, including habitat loss and shifting weather patterns', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Wind Power'), 'Energy Systems', NULL, 'What is the primary function of a microgrid?', '["It exclusively powers large industrial plants", "It replaces the national grid system", "It can operate independently or connect to the main grid", "It relies only on fossil fuel power sources"]'::jsonb, 2, 'It can operate independently or connect to the main grid', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Wind Power'), 'Energy Systems', NULL, 'What is a key difference between overhead and underground power transmission?', '["Underground transmission is cheaper to install", "Overhead transmission is more reliable in extreme weather", "Underground transmission is less susceptible to environmental damage", "Overhead transmission is immune to power losses"]'::jsonb, 2, 'Underground transmission is less susceptible to environmental damage', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false);


-- ─── 3. Record ingestion ──────────────────────────────────────
INSERT INTO ingestion_log (source_name, event_count, question_count, notes)
VALUES (
  'Badger Invitational 2025',
  5,
  136,
  'Division B only. Events: Ecology (50), Meteorology (20), Optics (12), Reach for the Stars (24), Wind Power (30). Extracted via pdfplumber + python-docx.'
)
ON CONFLICT (source_name) DO UPDATE SET
  event_count = EXCLUDED.event_count,
  question_count = EXCLUDED.question_count,
  notes = EXCLUDED.notes;