-- Part G: Meteorology -- batch 1/2
INSERT INTO quiz_questions (event_id, topic, subtopic, question, options, correct_index, correct_answer_text, explanation, difficulty, question_type, points, source_tournament, ai_generated)
VALUES
INSERT INTO quiz_questions (event_id, topic, subtopic, question, options, correct_index, correct_answer_text, explanation, difficulty, question_type, points, source_tournament, ai_generated)
VALUES
  ((SELECT id FROM events WHERE name = 'Meteorology'), 'Radiation and Albedo', NULL, 'Albedo is the amount of light absorbed by a surface, such as the Earth.', '["True", "False", "", ""]'::jsonb, 1, 'False', NULL, 'easy', 'true_false', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Meteorology'), 'Solar Radiation', NULL, 'The equator is warmer than the poles because there is more incoming solar radiation where the Earth''s shape bulges.', '["True", "False", "", ""]'::jsonb, 0, 'True', NULL, 'medium', 'true_false', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Meteorology'), 'Earth''s Surface', NULL, '70% of the earth''s surface is covered by ocean.', '["True", "False", "", ""]'::jsonb, 0, 'True', NULL, 'easy', 'true_false', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Meteorology'), 'Heat Capacity', NULL, 'Land absorbs and maintains heat better than the ocean.', '["True", "False", "", ""]'::jsonb, 1, 'False', NULL, 'medium', 'true_false', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Meteorology'), 'Ocean Oscillations', NULL, 'El Nino and La Nina are cold and warm phases in the Pacific Ocean.', '["True", "False", "", ""]'::jsonb, 0, 'True', NULL, 'medium', 'true_false', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Meteorology'), 'Climate and Weather', NULL, 'Climate is a specific event that happens over a short period and weather is the average weather conditions over a long period of time.', '["True", "False", "", ""]'::jsonb, 1, 'False', NULL, 'easy', 'true_false', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Meteorology'), 'Greenhouse Effect', NULL, 'Excess greenhouse gases in the atmosphere are the main reason global temperatures are increasing.', '["True", "False", "", ""]'::jsonb, 0, 'True', NULL, 'easy', 'true_false', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Meteorology'), 'Ocean and Coral', NULL, 'Increased ocean temperatures do not affect coral reefs in the ocean.', '["True", "False", "", ""]'::jsonb, 1, 'False', NULL, 'easy', 'true_false', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Meteorology'), 'Atmospheric Circulation', NULL, 'The Intertropical Convergence Zone (ITCZ) is caused by low pressure from intense solar heating over the equator.', '["True", "False", "", ""]'::jsonb, 0, 'True', NULL, 'medium', 'true_false', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Meteorology'), 'Atmospheric Layers', NULL, 'Which layer of the atmosphere contains the most ozone?', '["Troposphere", "Stratosphere", "Thermosphere", "Mesosphere"]'::jsonb, 1, 'Stratosphere', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false);
