-- Part L: Reach for the Stars -- batch 2/3
INSERT INTO quiz_questions (event_id, topic, subtopic, question, options, correct_index, correct_answer_text, explanation, difficulty, question_type, points, source_tournament, ai_generated)
VALUES
INSERT INTO quiz_questions (event_id, topic, subtopic, question, options, correct_index, correct_answer_text, explanation, difficulty, question_type, points, source_tournament, ai_generated)
VALUES
  ((SELECT id FROM events WHERE name = 'Reach for the Stars'), 'Stellar Evolution', NULL, 'All stars above 8 M end their life with a supernova.', '["True", "False", "", ""]'::jsonb, 0, 'True', NULL, 'hard', 'true_false', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Reach for the Stars'), 'Stellar Evolution', NULL, 'What event marks the start of the planetary nebula stage of a low to intermediate mass star''s life?', '["Start of ejecta ionization by star''s core", "End of core nuclear fusion", "End of shell nuclear fusion", "Start of large-scale mass loss in stellar envelope"]'::jsonb, 0, 'Start of ejecta ionization by star''s core', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Reach for the Stars'), 'White Dwarfs', NULL, 'Which physical phenomenon is most directly responsible for the electron degeneracy pressure that keeps white dwarfs from further collapse?', '["Strong nuclear force", "Electromagnetism", "Pauli exclusion principle", "Gravity"]'::jsonb, 2, 'Pauli exclusion principle', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Reach for the Stars'), 'White Dwarfs', NULL, 'Above what approximate mass is electron degeneracy pressure unable to stop a star''s core or a white dwarf from collapsing further?', '["1.18 M", "1.44 M", "1.62 M", "2.06 M"]'::jsonb, 1, '1.44 M', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Reach for the Stars'), 'White Dwarfs', NULL, 'Which two elements account for the largest portion of a white dwarf''s mass, given the progenitor star was of spectral type G during the main sequence?', '["Fe and Ni", "Si and Ne", "H and He", "C and O"]'::jsonb, 3, 'C and O', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Reach for the Stars'), 'Stellar Evolution', NULL, 'Which stage of stellar evolution begins when a low mass star begins helium fusion in its core?', '["Subgiant Branch", "Red Giant Branch", "Horizontal Branch", "Asymptotic Giant Branch"]'::jsonb, 2, 'Horizontal Branch', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Reach for the Stars'), 'Variable Stars', NULL, 'At the stage mentioned in the previous question, the stars can be further split on the HR-diagram into a red branch and a blue branch, separated by a gap on the instability strip. Which class of variable stars lies in this gap?', '["RR Lyrae variables", "Classic Cepheid variables", "Mira variables", "Wolf Rayet stars"]'::jsonb, 0, 'RR Lyrae variables', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Reach for the Stars'), 'Stellar Evolution', NULL, 'What mechanism is most directly responsible for the expansion in the outer envelope of a low mass star after core hydrogen fusion stops and before core helium fusion starts?', '["Coronal mass ejection", "Shell hydrogen fusion", "Core lithium fusion", "Stellar convection"]'::jsonb, 1, 'Shell hydrogen fusion', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Reach for the Stars'), 'Supernovae', NULL, 'What emissions spectral feature separates Type I and Type II supernovae?', '["Lack of any Hydrogen lines", "Presence Calcium II lines", "Lack of any Helium lines", "Presence of Oxygen lines"]'::jsonb, 0, 'Lack of any Hydrogen lines', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Reach for the Stars'), 'Supernovae', NULL, 'Which class of Type I supernova is the result of white dwarf accretion or white dwarfs merging, as opposed to stellar core collapse?', '["Type Ia", "Type Ib", "Type Ic", "Type Ipec"]'::jsonb, 0, 'Type Ia', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false);
