-- Part F: Ecology -- batch 5/5
INSERT INTO quiz_questions (event_id, topic, subtopic, question, options, correct_index, correct_answer_text, explanation, difficulty, question_type, points, source_tournament, ai_generated)
VALUES
INSERT INTO quiz_questions (event_id, topic, subtopic, question, options, correct_index, correct_answer_text, explanation, difficulty, question_type, points, source_tournament, ai_generated)
VALUES
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Habitat Fragmentation', NULL, 'Which of the following is the primary cause of habitat fragmentation in temperate grasslands?', '["Fire suppression policies", "Conversion to agricultural land", "Increased precipitation due to climate change", "Decline in herbivore populations"]'::jsonb, 1, 'Conversion to agricultural land', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Habitat Fragmentation', NULL, 'The "edge effect" resulting from habitat fragmentation typically leads to:', '["Increased genetic diversity in isolated populations", "Higher rates of predation and invasive species establishment", "Greater ecosystem stability and resilience", "Increased primary productivity in interior habitat zones"]'::jsonb, 1, 'Higher rates of predation and invasive species establishment', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Grassland Restoration', NULL, 'Which soil remediation technique is most effective in restoring nutrient-depleted grasslands?', '["Introduction of nitrogen-fixing plant species", "Clear-cutting of invasive woody vegetation", "Deep plowing to increase soil aeration", "Artificial wetland construction"]'::jsonb, 0, 'Introduction of nitrogen-fixing plant species', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Ecosystem Restoration', NULL, 'The introduction of keystone species into a disturbed ecosystem is an example of:', '["Passive restoration", "Ecological engineering", "Assisted migration", "Trophic rewilding"]'::jsonb, 3, 'Trophic rewilding', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Ecosystem Restoration', NULL, 'Which of the following best describes the goal of reconciliation ecology in habitat restoration?', '["Removing all human influence to restore historical ecosystem conditions", "Designing urban spaces and agricultural landscapes to support biodiversity", "Establishing strict no-use conservation zones to minimize human disturbance", "Utilizing genetically modified species to enhance ecosystem function"]'::jsonb, 1, 'Designing urban spaces and agricultural landscapes to support biodiversity', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Desertification Management', NULL, 'In response to desertification, a commonly implemented mitigation strategy involves:', '["Applying synthetic fertilizers to increase soil fertility", "Constructing windbreaks to reduce erosion and water loss", "Removing all vegetation to prevent further degradation", "Increasing groundwater extraction to support plant growth"]'::jsonb, 1, 'Constructing windbreaks to reduce erosion and water loss', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Habitat Degradation', NULL, 'Which factor contributes the most to "biotic homogenization" in degraded habitats?', '["Increased local adaptation of native species", "Expansion of invasive generalist species replacing specialists", "Reduced nutrient cycling due to lower decomposition rates", "Restoration of primary producer communities through seeding"]'::jsonb, 1, 'Expansion of invasive generalist species replacing specialists', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Restoration Techniques', NULL, 'What is the primary disadvantage of seed banks as a habitat restoration tool?', '["They reduce the genetic variability of wild plant populations", "They only store seeds of commercially valuable species", "Seeds may not germinate effectively in degraded soil conditions", "They accelerate genetic drift in natural populations"]'::jsonb, 2, 'Seeds may not germinate effectively in degraded soil conditions', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Grassland Restoration', NULL, 'Why is prescribed burning an effective restoration tool for some grassland ecosystems?', '["It increases water retention in the soil", "It removes invasive species while promoting fire-adapted native plants", "It enhances the carbon sequestration potential of the ecosystem", "It increases soil compaction, preventing erosion"]'::jsonb, 1, 'It removes invasive species while promoting fire-adapted native plants', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Restoration Techniques', NULL, 'Which of the following is a major challenge in using bioaugmentation for habitat restoration?', '["Difficulty in selecting appropriate microbial species", "Lack of available nutrients in restored soils", "High costs associated with implementing the technique", "Ineffectiveness in non-wetland ecosystems"]'::jsonb, 0, 'Difficulty in selecting appropriate microbial species', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false);
