-- Part E: Ecology -- batch 4/5
INSERT INTO quiz_questions (event_id, topic, subtopic, question, options, correct_index, correct_answer_text, explanation, difficulty, question_type, points, source_tournament, ai_generated)
VALUES
INSERT INTO quiz_questions (event_id, topic, subtopic, question, options, correct_index, correct_answer_text, explanation, difficulty, question_type, points, source_tournament, ai_generated)
VALUES
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Grassland Ecosystems', NULL, 'The primary difference between tallgrass and shortgrass prairie ecosystems is:', '["Soil nitrogen availability", "Fire frequency", "Annual precipitation levels", "Presence of large herbivores"]'::jsonb, 2, 'Annual precipitation levels', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Grassland Ecology', NULL, 'What role do mycorrhizal fungi play in grassland ecosystems?', '["They fix atmospheric nitrogen", "They enhance phosphorus uptake in plant roots", "They increase soil compaction", "They promote insect pollination"]'::jsonb, 1, 'They enhance phosphorus uptake in plant roots', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Grassland Ecology', NULL, 'What is the primary adaptation that allows grasses to survive extended droughts?', '["The ability to store water in above-ground stems", "Aerenchyma tissue development", "Extensive below-ground root systems", "High transpiration rates"]'::jsonb, 2, 'Extensive below-ground root systems', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Grassland Ecology', NULL, 'Which of the following processes is most responsible for the maintenance of grassland biodiversity?', '["Primary succession", "Fire suppression", "Periodic grazing and fire disturbance", "Increased CO2 concentration in the atmosphere"]'::jsonb, 2, 'Periodic grazing and fire disturbance', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Carbon Cycling', NULL, 'Grasslands contribute significantly to global carbon cycles through:', '["Carbon fixation by fast-growing woody plants", "The deep sequestration of organic material in soils", "Increased methane emissions from herbivores", "Rapid decomposition of above-ground biomass"]'::jsonb, 1, 'The deep sequestration of organic material in soils', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Grassland Ecology', NULL, 'Which of the following best explains why beta diversity is often higher in grassland ecosystems compared to forests?', '["Grasslands experience more frequent disturbances, leading to increased species turnover.", "Forests have higher species richness, which results in higher beta diversity.", "Grassland species are highly specialized, leading to low overlap between different locations.", "Grasslands have fewer primary producers, reducing competitive exclusion and increasing diversity."]'::jsonb, 0, 'Grasslands experience more frequent disturbances, leading to increased species turnover.', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Diversity Indices', NULL, 'The Shannon-Wiener Index (H'') is commonly used to measure biodiversity. If a grassland ecosystem has an H'' value close to zero, what does this indicate?', '["High species evenness but low richness", "A dominance of a single species with very low diversity", "A perfectly even distribution of species", "High richness but low evenness"]'::jsonb, 1, 'A dominance of a single species with very low diversity', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Grassland Ecology', NULL, 'Which of the following processes contributes the most to functional redundancy in grassland biodiversity?', '["Low genetic variation within individual species populations", "Strong interspecific competition leading to niche differentiation", "Frequent herbivory reducing plant species dominance", "High niche overlap among plant species"]'::jsonb, 3, 'High niche overlap among plant species', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Species-Area Relationship', NULL, 'According to the species-area relationship (S = cA^z), what is the most likely consequence of habitat fragmentation in a temperate grassland ecosystem?', '["Loss of specialist species due to reduced available habitat", "Increase in ecosystem stability due to reduced species interactions", "Increased species richness as smaller patches provide unique microhabitats", "Lower extinction rates due to decreased competition for resources"]'::jsonb, 0, 'Loss of specialist species due to reduced available habitat', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Ecology'), 'Grassland Conservation', NULL, 'In the context of grassland biodiversity conservation, why is the introduction of non-native C4 grasses often problematic?', '["Non-native grasses increase nitrogen fixation, altering soil nutrient cycling.", "They outcompete native C3 grasses, reducing plant species diversity and ecosystem function.", "They increase CO2 sequestration, leading to changes in microbial diversity.", "Non-native grasses provide less food for herbivores, leading to trophic cascades."]'::jsonb, 1, 'They outcompete native C3 grasses, reducing plant species diversity and ecosystem function.', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false);
