-- Part H: Meteorology -- batch 2/2
INSERT INTO quiz_questions (event_id, topic, subtopic, question, options, correct_index, correct_answer_text, explanation, difficulty, question_type, points, source_tournament, ai_generated)
VALUES
INSERT INTO quiz_questions (event_id, topic, subtopic, question, options, correct_index, correct_answer_text, explanation, difficulty, question_type, points, source_tournament, ai_generated)
VALUES
  ((SELECT id FROM events WHERE name = 'Meteorology'), 'Greenhouse Gases', NULL, 'What is the primary greenhouse gas in Earth''s atmosphere?', '["Methane (CH4)", "Fluorinated gases", "Carbon Dioxide (CO2)", "Nitrous Oxide (N2O)"]'::jsonb, 2, 'Carbon Dioxide (CO2)', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Meteorology'), 'Feedback Loops', NULL, 'Which of the following is true when there is ice-albedo feedback? (Select all that apply)', '["Temperatures warm and ice starts to melt", "Albedo of Earth decreases", "Further warming occurs", "All the above"]'::jsonb, 3, 'All the above', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Meteorology'), 'Climate Change', NULL, 'During the last ice age, atmospheric CO2 and CH4 concentrations were lower looking at air trapped in ice cores. What trend in CO2 would we see since the last ice age considering our current climate and future climate projections?', '["Continuous decreases in CO2 concentrations", "Aggressive increase in CO2 concentrations", "CO2 concentrations would remain the same", "None of the above"]'::jsonb, 1, 'Aggressive increase in CO2 concentrations', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Meteorology'), 'Ocean Energy', NULL, 'The ocean is the largest solar energy collector on Earth, while also collecting longwave radiation from the Earth''s surface that can''t escape to space. What impact does this collection of radiation have on the ocean temperatures?', '["Temperatures stay the same", "Temperature decrease", "Temperatures increase", "None of the above"]'::jsonb, 2, 'Temperatures increase', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Meteorology'), 'Climate Data', NULL, 'What is the minimum time interval used for data to be considered "climatic data"?', '["30 years", "50 years", "100 years", "10 years"]'::jsonb, 0, '30 years', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Meteorology'), 'Solar Radiation Variation', NULL, 'What climatic region experiences the largest variation in daylight throughout the year due to the Earth''s tilt?', '["Polar regions", "Deserts", "Rainforests", "Tropical islands"]'::jsonb, 0, 'Polar regions', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Meteorology'), 'Meteorology Scales', NULL, 'Which of the following is NOT a temporal or spatial scale of meteorology?', '["Synoptic", "Tropical", "Microscale", "Mesoscale"]'::jsonb, 1, 'Tropical', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Meteorology'), 'Ocean Currents', NULL, 'Ocean gyres are large systems of circular currents in the ocean. Which two factors influence their formation?', '["Global wind patterns and Low pressure systems", "Temperature gradients and Forces created by Earth''s rotation", "Forces created by Earth''s rotation", "Global wind patterns"]'::jsonb, 3, 'Global wind patterns and Forces created by Earth''s rotation', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Meteorology'), 'Climate Sensitivity', NULL, 'Climate sensitivity is often expressed in units of _________.', '["\u00b0C/W", "\u00b0C/J", "\u00b0C/(W/m\u00b2)", "\u00b0C/(W/m)"]'::jsonb, 2, '°C/(W/m²)', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Meteorology'), 'Sea Level', NULL, 'Which of the following can result from a global rise or fall in sea level?', '["Local variations in ocean temperature", "Melting ice sheets", "Extreme rainfall from tropical cyclones", "A change in ocean density"]'::jsonb, 1, 'Melting ice sheets', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false);
