-- Part P: Wind Power -- batch 3/3
INSERT INTO quiz_questions (event_id, topic, subtopic, question, options, correct_index, correct_answer_text, explanation, difficulty, question_type, points, source_tournament, ai_generated)
VALUES
INSERT INTO quiz_questions (event_id, topic, subtopic, question, options, correct_index, correct_answer_text, explanation, difficulty, question_type, points, source_tournament, ai_generated)
VALUES
  ((SELECT id FROM events WHERE name = 'Wind Power'), 'Energy Conversion', NULL, 'What is the primary purpose of a rectifier?', '["To convert AC to DC", "To store electrical energy", "To step up voltage", "To convert DC to AC"]'::jsonb, 0, 'To convert AC to DC', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Wind Power'), 'Electrical Systems', NULL, 'What role do wind turbine inverters play in grid synchronization?', '["They increase the speed of wind turbines", "They match the voltage, frequency, and phase with the grid", "They generate additional power from fossil fuels", "They store excess power in batteries"]'::jsonb, 1, 'They match the voltage, frequency, and phase with the grid', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Wind Power'), 'Energy Storage', NULL, 'What is the primary difference between a supercapacitor and a traditional capacitor?', '["Supercapacitors store energy chemically, while traditional capacitors store it electrostatically", "Supercapacitors have a dielectric material, while traditional capacitors do not", "Supercapacitors store energy electrostatically with an electrolyte, allowing higher energy density", "Traditional capacitors have higher energy density than supercapacitors"]'::jsonb, 2, 'Supercapacitors store energy electrostatically with an electrolyte, allowing higher energy density', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Wind Power'), 'Energy Conversion', NULL, 'Why do superconductors exhibit zero electrical resistance?', '["Electrons move faster at low temperatures", "Electrons form Cooper pairs, allowing resistance-free movement", "Superconductors have a special insulation layer", "Magnetic fields inside superconductors generate current without resistance"]'::jsonb, 1, 'Electrons form Cooper pairs, allowing resistance-free movement', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Wind Power'), 'Energy Conversion', NULL, 'What is a key advantage of high-temperature superconductors (HTS) over traditional superconductors?', '["They do not require cooling", "They can operate above the boiling point of liquid nitrogen", "They are cheaper to manufacture than copper wires", "They can be used at room temperature"]'::jsonb, 1, 'They can operate above the boiling point of liquid nitrogen', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Wind Power'), 'Energy Sources', NULL, 'Which renewable energy source has the lowest GHG emissions?', '["Hydropower", "Solar PV", "Wind power", "Geothermal"]'::jsonb, 2, 'Wind power', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Wind Power'), 'Climate Change', NULL, 'What is the primary mechanism by which CO2 emissions contribute to climate change?', '["Ice core samples contain fossilized plants", "Ice core samples show constant CO2 levels over time", "CO2 levels in ice cores correlate with temperature changes over glacial cycles", "Ice core samples have no relation to CO2 measurements"]'::jsonb, 2, 'CO2 levels in ice cores correlate with temperature changes over glacial cycles', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Wind Power'), 'Climate Change', NULL, 'How does a small temperature increase (e.g. 1.2°C) affect global ecosystems?', '["It has no significant effects", "It causes widespread changes, including habitat loss and shifting weather patterns", "It only affects regions near the equator", "It improves conditions for all plant life"]'::jsonb, 1, 'It causes widespread changes, including habitat loss and shifting weather patterns', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Wind Power'), 'Energy Systems', NULL, 'What is the primary function of a microgrid?', '["It exclusively powers large industrial plants", "It replaces the national grid system", "It can operate independently or connect to the main grid", "It relies only on fossil fuel power sources"]'::jsonb, 2, 'It can operate independently or connect to the main grid', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Wind Power'), 'Energy Systems', NULL, 'What is a key difference between overhead and underground power transmission?', '["Underground transmission is cheaper to install", "Overhead transmission is more reliable in extreme weather", "Underground transmission is less susceptible to environmental damage", "Overhead transmission is immune to power losses"]'::jsonb, 2, 'Underground transmission is less susceptible to environmental damage', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false);
