-- Part N: Wind Power -- batch 1/3
INSERT INTO quiz_questions (event_id, topic, subtopic, question, options, correct_index, correct_answer_text, explanation, difficulty, question_type, points, source_tournament, ai_generated)
VALUES
INSERT INTO quiz_questions (event_id, topic, subtopic, question, options, correct_index, correct_answer_text, explanation, difficulty, question_type, points, source_tournament, ai_generated)
VALUES
  ((SELECT id FROM events WHERE name = 'Wind Power'), 'Blade Design', NULL, 'What is the main function of the pitch system in a wind turbine?', '["Converting wind energy into mechanical energy", "Adjusting blade angles for optimal rotor speed", "Supporting the main shaft", "Stopping the rotor in emergency situations"]'::jsonb, 1, 'Adjusting blade angles for optimal rotor speed', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Wind Power'), 'Blade Design', NULL, 'What does the yaw system do in a wind turbine?', '["Changes the angle of attack", "Rotates the nacelle to align with wind direction", "Stops the rotor during maintenance", "Controls electricity output"]'::jsonb, 1, 'Rotates the nacelle to align with wind direction', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Wind Power'), 'Energy Conversion', NULL, 'What principle explains how wind turbine blades generate lift?', '["Pascal''s Principle", "Bernoulli''s Principle", "Newton''s First Law", "Archimedes'' Principle"]'::jsonb, 1, 'Bernoulli''s Principle', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Wind Power'), 'Blade Design', NULL, 'Why are wind turbine blades twisted?', '["To reduce material cost", "To allow each section of the blade to have an optimal angle of attack", "To decrease rotor speed", "To prevent structural damage"]'::jsonb, 1, 'To allow each section of the blade to have an optimal angle of attack', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Wind Power'), 'Blade Design', NULL, 'What is the optimal strategy for regulating turbine rotational speed in high wind conditions?', '["Increase the angle of attack", "Active stall control", "Decrease the blade twist", "Increase the number of blades"]'::jsonb, 1, 'Active stall control', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Wind Power'), 'Energy Conversion', NULL, 'What is the primary use of a transformer?', '["To increase resistance", "To store electrical energy", "To change the voltage level in an AC circuit", "To block DC currents"]'::jsonb, 2, 'To change the voltage level in an AC circuit', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Wind Power'), 'Electrical Systems', NULL, 'What happens to the current in a purely resistive AC circuit?', '["It leads voltage by 90 degrees", "It lags behind voltage by 90 degrees", "It is in phase with the voltage", "There is no current flow"]'::jsonb, 2, 'It is in phase with the voltage', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Wind Power'), 'Electrical Systems', NULL, 'Which of the following devices stores energy in a magnetic field?', '["Resistor", "Capacitor", "Inductor", "Transformer"]'::jsonb, 2, 'Inductor', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Wind Power'), 'Electrical Systems', NULL, 'Active power in an AC circuit is measured in:', '["VA (Volt-Amperes)", "Watts", "Ohms", "Farads"]'::jsonb, 1, 'Watts', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Wind Power'), 'Electrical Systems', NULL, 'The unit of capacitance is:', '["Ohms", "Farads", "Henrys", "Joules"]'::jsonb, 1, 'Farads', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false);
