-- Part I: Optics -- batch 1/2
INSERT INTO quiz_questions (event_id, topic, subtopic, question, options, correct_index, correct_answer_text, explanation, difficulty, question_type, points, source_tournament, ai_generated)
VALUES
INSERT INTO quiz_questions (event_id, topic, subtopic, question, options, correct_index, correct_answer_text, explanation, difficulty, question_type, points, source_tournament, ai_generated)
VALUES
  ((SELECT id FROM events WHERE name = 'Optics'), 'Light and Color', NULL, 'Which of the following best explains why the sky appears blue?', '["The atmosphere preferentially scatters shorter wavelengths of light", "The ocean reflects blue light into the sky", "Air molecules absorb red light and emit blue light", "The human eye is more sensitive to blue than red in daylight"]'::jsonb, 0, 'The atmosphere preferentially scatters shorter wavelengths of light', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Optics'), 'Reflection', NULL, 'Which of the following is NOT an example of specular reflection?', '["Light reflecting off a calm lake", "Light reflecting off a polished metal surface", "Light reflecting off a white sheet of paper", "Light reflecting off a smooth glass window"]'::jsonb, 2, 'Light reflecting off a white sheet of paper', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Optics'), 'Mirrors', NULL, 'Why can you always see your full body in a mirror that is only half your height?', '["The mirror bends light to make you look smaller", "The mirror magnifies the image", "Light reflects symmetrically, so only half is needed to capture your full reflection", "The brain adjusts the image automatically"]'::jsonb, 2, 'Light reflects symmetrically, so only half is needed to capture your full reflection', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Optics'), 'Color and Light', NULL, 'Why does a red apple appear red under white light?', '["It absorbs red light and reflects all other colors", "It reflects red light and absorbs all other colors", "It absorbs blue and green light but reflects red light", "It emits red light on its own"]'::jsonb, 2, 'It absorbs blue and green light but reflects red light', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Optics'), 'Color and Light', NULL, 'Which of the following statements is TRUE about the primary colors of light?', '["Mixing red and blue light creates yellow", "The primary colors of light are red, blue, and green", "The primary colors of light are the same as pigment colors", "White light is made by mixing cyan, magenta, and yellow"]'::jsonb, 1, 'The primary colors of light are red, blue, and green', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Optics'), 'Color and Light', NULL, 'What color will a yellow object appear if illuminated by pure blue light?', '["Yellow", "Green", "Black", "White"]'::jsonb, 2, 'Black', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Optics'), 'Eye Anatomy', NULL, 'Which part of the eye controls the amount of light entering the pupil?', '["Cornea", "Lens", "Iris", "Retina"]'::jsonb, 2, 'Iris', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Optics'), 'Eye Conditions', NULL, 'Which of the following conditions is caused by the eyeball being too long, causing distant objects to appear blurry?', '["Hyperopia (Farsightedness)", "Myopia (Nearsightedness)", "Astigmatism", "Presbyopia"]'::jsonb, 1, 'Myopia (Nearsightedness)', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Optics'), 'Eye Conditions', NULL, 'A person with astigmatism has difficulty seeing clearly because:', '["Their eye lens is too rigid", "Their cornea or lens is irregularly shaped", "Their retina is damaged", "Their optic nerve is underdeveloped"]'::jsonb, 1, 'Their cornea or lens is irregularly shaped', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Optics'), 'Mirrors', NULL, 'What type of image does a plane mirror always produce?', '["Real and inverted", "Real and upright", "Virtual and inverted", "Virtual and upright"]'::jsonb, 3, 'Virtual and upright', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false);
