-- ═══════════════════════════════════════════════════════════════
--  Migration 022: Import Heredity B Questions
--
--  Imports 50 questions from Badger Invitational 2025
--  Heredity B test (Division B)
-- ═══════════════════════════════════════════════════════════════

-- ── Heredity (50 questions) ──
-- batch 1/5
INSERT INTO quiz_questions (event_id, topic, subtopic, question, options, correct_index, correct_answer_text, explanation, difficulty, question_type, points, source_tournament, ai_generated)
VALUES
  ((SELECT id FROM events WHERE name = 'Heredity'), 'RNA Structure and Function', NULL, 'Which base is found in RNA but not in DNA?', '["Thymine", "Adenine", "Cytosine", "Uracil"]'::jsonb, 3, 'Uracil', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'Sex-Linked Inheritance', NULL, 'Hemophilia B is caused by a mutation in which gene?', '["Factor VIII", "Factor IX", "Factor V", "Factor XII"]'::jsonb, 1, 'Factor IX', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'RNA Structure and Function', NULL, 'The enzyme responsible for synthesizing RNA during transcription is:', '["DNA polymerase", "RNA ligase", "RNA polymerase", "Helicase"]'::jsonb, 2, 'RNA polymerase', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'Chromatin Structure', NULL, 'Which type of chromatin is more tightly packed and generally inactive?', '["Euchromatin", "Heterochromatin", "Polychromatin", "Metachromatin"]'::jsonb, 1, 'Heterochromatin', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'PCR', NULL, 'PCR works by cycling through which series of steps?', '["Denaturation \u2192 Annealing \u2192 Extension", "Initiation \u2192 Elongation \u2192 Termination", "Unwinding \u2192 Splicing \u2192 Translation", "Replication \u2192 Proofreading \u2192 Repair"]'::jsonb, 0, 'Denaturation → Annealing → Extension', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'Mendelian Genetics', NULL, 'Mendel’s Law of Segregation states that:', '["Genes on the same chromosome are inherited together", "Alleles segregate during gamete formation, so each gamete carries only one allele", "Some alleles are dominant while others are recessive", "Traits are blended in offspring"]'::jsonb, 1, 'Alleles segregate during gamete formation, so each gamete carries only one allele', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'Punnett Squares', NULL, 'In a cross Aa × Aa, what is the expected genotypic ratio of the offspring?', '["1:2:1", "3:1", "1:1", "9:3:3:1"]'::jsonb, 0, '1:2:1', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'Dominance and Gene Interactions', NULL, 'Which of the following is an example of codominance?', '["Red flower \u00d7 white flower = pink flower", "Blood type AB", "Black fur dominant over white fur", "Height in humans"]'::jsonb, 1, 'Blood type AB', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'Epistasis', NULL, 'Recessive epistasis occurs when:', '["A dominant allele masks a recessive allele", "Two dominant alleles interact to create a new phenotype", "A homozygous recessive allele at one locus masks the expression of another gene", "Two genes are inherited independently"]'::jsonb, 2, 'A homozygous recessive allele at one locus masks the expression of another gene', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'Pedigree Analysis', NULL, 'A pedigree shows a trait appearing in every generation. This suggests the trait is likely:', '["Autosomal recessive", "Autosomal dominant", "Sex-linked recessive", "Sex-linked dominant"]'::jsonb, 1, 'Autosomal dominant', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false);

-- batch 2/5
INSERT INTO quiz_questions (event_id, topic, subtopic, question, options, correct_index, correct_answer_text, explanation, difficulty, question_type, points, source_tournament, ai_generated)
VALUES
  ((SELECT id FROM events WHERE name = 'Heredity'), 'Sex-Linked Inheritance', NULL, 'If a gene is X-linked recessive, a male with the allele will:', '["Always express the trait", "Express the trait only if homozygous", "Never express the trait", "Pass the allele to all sons"]'::jsonb, 0, 'Always express the trait', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'Dominance and Gene Interactions', NULL, 'In incomplete dominance, the heterozygous phenotype is:', '["Identical to the dominant parent", "A blend of the two parents", "The same as the recessive parent", "Unchanged"]'::jsonb, 1, 'A blend of the two parents', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'Punnett Squares', NULL, 'In a dihybrid cross AaBb × AaBb, what is the probability that offspring will be homozygous recessive for both traits?', '["1/16", "1/4", "1/8", "9/16"]'::jsonb, 0, '1/16', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'Punnett Squares', NULL, 'In a testcross, an unknown dominant phenotype is crossed with a homozygous recessive individual. This is done to:', '["Determine if the unknown is homozygous or heterozygous", "Increase genetic variation", "Produce all dominant offspring", "Test for codominance"]'::jsonb, 0, 'Determine if the unknown is homozygous or heterozygous', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'General Genetics', NULL, 'Chargaff’s rules state that in DNA:', '["A = T and C = G", "A = C and T = G", "Purines pair with purines", "Pyrimidines pair with purines"]'::jsonb, 0, 'A = T and C = G', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'DNA Structure', NULL, 'Which one of the choices contains only purines?', '["C, G", "T, G", "C, T", "A, G"]'::jsonb, 3, 'A, G', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'DNA Structure', NULL, 'What distinguishes purines and pyrimidines?', '["Purines are single-ringed; pyrimidines are double-ringed", "Purines pair with purines; pyrimidines pair with pyrimidines", "Purines are double-ringed; pyrimidines are single-ringed", "Purines are only in RNA; pyrimidines are only in DNA"]'::jsonb, 2, 'Purines are double-ringed; pyrimidines are single-ringed', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'DNA Replication', NULL, 'During DNA replication, which of the following holds the strands apart from each other?', '["DNA ligase", "Helicase", "Single-strand binding proteins (SSBs)", "DNA polymerase"]'::jsonb, 2, 'Single-strand binding proteins (SSBs)', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'RNA Processing', NULL, 'What is the purpose of the poly-A tail?', '["Marks the RNA for transcription initiation", "Protects mRNA from degradation and aids in export from the nucleus", "Serves as a primer for DNA replication", "Guides tRNA to the ribosome"]'::jsonb, 1, 'Protects mRNA from degradation and aids in export from the nucleus', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'Translation', NULL, 'Which of the choices below contains the three sites within a ribosome?', '["A site, P site, E site", "Alpha, beta, gamma sites", "Codon, anticodon, promoter sites", "Initiation, elongation, termination sites"]'::jsonb, 0, 'A site, P site, E site', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false);

-- batch 3/5
INSERT INTO quiz_questions (event_id, topic, subtopic, question, options, correct_index, correct_answer_text, explanation, difficulty, question_type, points, source_tournament, ai_generated)
VALUES
  ((SELECT id FROM events WHERE name = 'Heredity'), 'Translation', NULL, 'Which of the choices contains the areas of a cell in which protein synthesis occurs?', '["Nucleus and mitochondria", "Cytosol and rough endoplasmic reticulum", "Smooth endoplasmic reticulum and Golgi apparatus", "Smooth endoplasmic reticulum and rough endoplasmic reticulum"]'::jsonb, 1, 'Cytosol and rough endoplasmic reticulum', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'DNA Sequencing', NULL, 'Which of the following describes Sanger sequencing?', '["Uses RNA polymerase to make mRNA", "Incorporates dideoxynucleotides to terminate DNA synthesis at specific bases", "Amplifies DNA using thermal cycling", "Creates complementary RNA from DNA"]'::jsonb, 1, 'Incorporates dideoxynucleotides to terminate DNA synthesis at specific bases', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'General Genetics', NULL, 'A single base deletion in DNA may cause:', '["Missense mutation", "Nonsense mutation", "Frameshift mutation", "Silent mutation"]'::jsonb, 2, 'Frameshift mutation', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'Central Dogma', NULL, 'The central dogma of molecular biology states:', '["Protein \u2192 RNA \u2192 DNA", "DNA \u2192 RNA \u2192 Protein", "RNA \u2192 DNA \u2192 Protein", "Protein \u2192 DNA \u2192 RNA"]'::jsonb, 1, 'DNA → RNA → Protein', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'RNA Structure and Function', NULL, 'During transcription, RNA polymerase moves along:', '["5\u2019 \u2192 3\u2019 of the template strand", "3\u2019 \u2192 5\u2019 of the template strand", "3\u2019 \u2192 5\u2019 of the coding strand", "Randomly"]'::jsonb, 1, '3'' → 5'' of the template strand', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'RNA Structure and Function', NULL, 'tRNA functions to:', '["Carry genetic information", "Carry amino acids to the ribosome", "Make peptide bonds", "Unwind DNA"]'::jsonb, 1, 'Carry amino acids to the ribosome', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'PCR', NULL, 'During PCR, denaturation occurs at:', '["50\u201360\u00b0C", "70\u201375\u00b0C", "94\u201398\u00b0C", "37\u00b0C"]'::jsonb, 2, '94–98°C', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'PCR', NULL, 'The role of primers in PCR is to:', '["Unwind the DNA", "Provide a starting point for DNA polymerase", "Cut DNA at specific sites", "Terminate synthesis"]'::jsonb, 1, 'Provide a starting point for DNA polymerase', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'PCR', NULL, 'Sanger sequencing differs from PCR because:', '["It uses RNA polymerase", "It uses dideoxynucleotides to terminate DNA synthesis", "It requires no primers", "It produces proteins"]'::jsonb, 1, 'It uses dideoxynucleotides to terminate DNA synthesis', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'PCR', NULL, 'PCR can be used to:', '["Amplify a specific DNA fragment", "Determine chromosome number", "Visualize ribosomes", "Transcribe RNA"]'::jsonb, 0, 'Amplify a specific DNA fragment', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false);

-- batch 4/5
INSERT INTO quiz_questions (event_id, topic, subtopic, question, options, correct_index, correct_answer_text, explanation, difficulty, question_type, points, source_tournament, ai_generated)
VALUES
  ((SELECT id FROM events WHERE name = 'Heredity'), 'DNA Sequencing', NULL, 'In Sanger sequencing, the incorporation of a dideoxynucleotide results in:', '["Extension of the DNA strand", "Termination of DNA strand elongation", "Formation of RNA", "Replication of the whole genome"]'::jsonb, 1, 'Termination of DNA strand elongation', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'Chromosome Structure', NULL, 'What is the primary function of telomeres in eukaryotic chromosomes?', '["They code for proteins that regulate the cell cycle", "They prevent the loss of important DNA sequences during replication", "They serve as origins of replication", "They attach chromosomes to the nuclear membrane"]'::jsonb, 1, 'They prevent the loss of important DNA sequences during replication', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'DNA Replication', NULL, 'In DNA replication, the leading strand is synthesized continuously because:', '["DNA polymerase can synthesize in both directions", "Helicase only unwinds in short segments", "DNA polymerase moves in the same direction as fork unwinding", "Okazaki fragments only form on the template strand"]'::jsonb, 2, 'DNA polymerase moves in the same direction as fork unwinding', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'Mutations', NULL, 'A mutation changes a codon from UAU to UAA. This mutation most directly:', '["Substitutes one amino acid for another", "Introduces a premature stop codon", "Has no effect on the encoded protein", "Shifts the reading frame"]'::jsonb, 1, 'Introduces a premature stop codon', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'Sex-Linked Inheritance', NULL, 'A woman is heterozygous for an X-linked recessive disorder, and her partner is unaffected. What proportion of their sons are expected to be affected?', '["0%", "25%", "50%", "100%"]'::jsonb, 2, '50%', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'Punnett Squares', NULL, 'In a cross AaBb x aabb, the offspring show equal numbers of AaBb, Aabb, aaBb, and aabb. This results most strongly suggests that:', '["A and B are linked", "A and B assort independently", "A is epistatic to B", "The cross involved incomplete dominance"]'::jsonb, 1, 'A and B assort independently', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'Transcription', NULL, 'In the lac operon, which condition best explains low but nonzero transcription?', '["High glucose, no lactose", "High glucose, high lactose", "Low glucose, no lactose", "Low glucose, high lactose"]'::jsonb, 1, 'High glucose, high lactose', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'Punnett Squares', NULL, 'Crossing over between two linked genes occurs in 18%  of meioses. In a testcross of an AB/ab individual with ab/ab, what fraction of offspring are parental types?', '["9%", "18%", "41%", "82%"]'::jsonb, 3, '82%', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'Mutations', NULL, 'A base substitution in an exon does not change the amino acid sequence. The best term for this mutation is:', '["Silent", "Missense", "Nonsense", "Frameshift"]'::jsonb, 0, 'Silent', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'Punnett Squares', NULL, 'In a dihybrid testcross of an individual with AB/ab genotype and an individual with ab/ab, the following phenotypic ratios were observed: 420 AB, 80 Ab, 70 aB, 430 ab. What is the recombination frequency between A and B?', '["7%", "15%", "23%", "50%"]'::jsonb, 1, '15%', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false);

-- batch 5/5
INSERT INTO quiz_questions (event_id, topic, subtopic, question, options, correct_index, correct_answer_text, explanation, difficulty, question_type, points, source_tournament, ai_generated)
VALUES
  ((SELECT id FROM events WHERE name = 'Heredity'), 'RNA Structure and Function', NULL, 'Uracil is a base in DNA.', '["True", "False", "", ""]'::jsonb, 1, 'False', NULL, 'easy', 'true_false', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'Sex-Linked Inheritance', NULL, 'Hemophilia B is a sex-linked recessive disorder.', '["True", "False", "", ""]'::jsonb, 0, 'True', NULL, 'easy', 'true_false', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'General Genetics', NULL, 'The p-arm is the longer arm of a chromosome.', '["True", "False", "", ""]'::jsonb, 1, 'False', NULL, 'easy', 'true_false', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'Chromatin Structure', NULL, 'Heterochromatin is genetically active.', '["True", "False", "", ""]'::jsonb, 1, 'False', NULL, 'easy', 'true_false', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'Transcription', NULL, 'The stages of transcription are initiation, elongation, and termination.', '["True", "False", "", ""]'::jsonb, 0, 'True', NULL, 'easy', 'true_false', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'RNA Structure and Function', NULL, 'mRNA assists in attaching amino acids to each other.', '["True", "False", "", ""]'::jsonb, 1, 'False', NULL, 'easy', 'true_false', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'PCR', NULL, 'Taq polymerase is used to perform PCR.', '["True", "False", "", ""]'::jsonb, 0, 'True', NULL, 'easy', 'true_false', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'RNA Structure and Function', NULL, 'The ribosome is made of rRNA and proteins.', '["True", "False", "", ""]'::jsonb, 0, 'True', NULL, 'easy', 'true_false', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'DNA Replication', NULL, 'DNA replication is semiconservative.', '["True", "False", "", ""]'::jsonb, 0, 'True', NULL, 'easy', 'true_false', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'Mutations', NULL, 'A codon consists of two nucleotides.', '["True", "False", "", ""]'::jsonb, 1, 'False', NULL, 'easy', 'true_false', 1, 'Badger Invitational 2025', false);

-- Update ingestion log
UPDATE ingestion_log SET
  question_count = question_count + 50,
  event_count = event_count + 1,
  notes = notes || ' + Heredity (50 questions).'
WHERE source_name = 'Badger Invitational 2025';

-- If no row existed yet, insert one
INSERT INTO ingestion_log (source_name, event_count, question_count, notes)
SELECT 'Badger Invitational 2025', 1, 50, 'Heredity (50 questions).'
WHERE NOT EXISTS (SELECT 1 FROM ingestion_log WHERE source_name = 'Badger Invitational 2025');