-- Part C: Heredity -- batch 2/5
INSERT INTO quiz_questions (event_id, topic, subtopic, question, options, correct_index, correct_answer_text, explanation, difficulty, question_type, points, source_tournament, ai_generated)
VALUES
INSERT INTO quiz_questions (event_id, topic, subtopic, question, options, correct_index, correct_answer_text, explanation, difficulty, question_type, points, source_tournament, ai_generated)
VALUES
  ((SELECT id FROM events WHERE name = 'Heredity'), 'Sex-Linked Inheritance', NULL, 'If a gene is X-linked recessive, a male with the allele will:', '["Always express the trait", "Express the trait only if homozygous", "Never express the trait", "Pass the allele to all sons"]'::jsonb, 0, 'Always express the trait', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'Dominance and Gene Interactions', NULL, 'In incomplete dominance, the heterozygous phenotype is:', '["Identical to the dominant parent", "A blend of the two parents", "The same as the recessive parent", "Unchanged"]'::jsonb, 1, 'A blend of the two parents', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'Punnett Squares', NULL, 'In a dihybrid cross AaBb × AaBb, what is the probability that offspring will be homozygous recessive for both traits?', '["1/16", "1/4", "1/8", "9/16"]'::jsonb, 0, '1/16', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'Punnett Squares', NULL, 'In a testcross, an unknown dominant phenotype is crossed with a homozygous recessive individual. This is done to:', '["Determine if the unknown is homozygous or heterozygous", "Increase genetic variation", "Produce all dominant offspring", "Test for codominance"]'::jsonb, 0, 'Determine if the unknown is homozygous or heterozygous', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'General Genetics', NULL, 'Chargaff’s rules state that in DNA:', '["A = T and C = G", "A = C and T = G", "Purines pair with purines", "Pyrimidines pair with purines"]'::jsonb, 0, 'A = T and C = G', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'DNA Structure', NULL, 'Which one of the choices contains only purines?', '["C, G", "T, G", "C, T", "A, G"]'::jsonb, 3, 'A, G', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'DNA Structure', NULL, 'What distinguishes purines and pyrimidines?', '["Purines are single-ringed;
