-- Part E: Heredity -- batch 4/5
INSERT INTO quiz_questions (event_id, topic, subtopic, question, options, correct_index, correct_answer_text, explanation, difficulty, question_type, points, source_tournament, ai_generated)
VALUES
INSERT INTO quiz_questions (event_id, topic, subtopic, question, options, correct_index, correct_answer_text, explanation, difficulty, question_type, points, source_tournament, ai_generated)
VALUES
  ((SELECT id FROM events WHERE name = 'Heredity'), 'DNA Sequencing', NULL, 'In Sanger sequencing, the incorporation of a dideoxynucleotide results in:', '["Extension of the DNA strand", "Termination of DNA strand elongation", "Formation of RNA", "Replication of the whole genome"]'::jsonb, 1, 'Termination of DNA strand elongation', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'Chromosome Structure', NULL, 'What is the primary function of telomeres in eukaryotic chromosomes?', '["They code for proteins that regulate the cell cycle", "They prevent the loss of important DNA sequences during replication", "They serve as origins of replication", "They attach chromosomes to the nuclear membrane"]'::jsonb, 1, 'They prevent the loss of important DNA sequences during replication', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'DNA Replication', NULL, 'In DNA replication, the leading strand is synthesized continuously because:', '["DNA polymerase can synthesize in both directions", "Helicase only unwinds in short segments", "DNA polymerase moves in the same direction as fork unwinding", "Okazaki fragments only form on the template strand"]'::jsonb, 2, 'DNA polymerase moves in the same direction as fork unwinding', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'Mutations', NULL, 'A mutation changes a codon from UAU to UAA. This mutation most directly:', '["Substitutes one amino acid for another", "Introduces a premature stop codon", "Has no effect on the encoded protein", "Shifts the reading frame"]'::jsonb, 1, 'Introduces a premature stop codon', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'Sex-Linked Inheritance', NULL, 'A woman is heterozygous for an X-linked recessive disorder, and her partner is unaffected. What proportion of their sons are expected to be affected?', '["0%", "25%", "50%", "100%"]'::jsonb, 2, '50%', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'Punnett Squares', NULL, 'In a cross AaBb x aabb, the offspring show equal numbers of AaBb, Aabb, aaBb, and aabb. This results most strongly suggests that:', '["A and B are linked", "A and B assort independently", "A is epistatic to B", "The cross involved incomplete dominance"]'::jsonb, 1, 'A and B assort independently', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'Transcription', NULL, 'In the lac operon, which condition best explains low but nonzero transcription?', '["High glucose, no lactose", "High glucose, high lactose", "Low glucose, no lactose", "Low glucose, high lactose"]'::jsonb, 1, 'High glucose, high lactose', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'Punnett Squares', NULL, 'Crossing over between two linked genes occurs in 18%  of meioses. In a testcross of an AB/ab individual with ab/ab, what fraction of offspring are parental types?', '["9%", "18%", "41%", "82%"]'::jsonb, 3, '82%', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'Mutations', NULL, 'A base substitution in an exon does not change the amino acid sequence. The best term for this mutation is:', '["Silent", "Missense", "Nonsense", "Frameshift"]'::jsonb, 0, 'Silent', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'Punnett Squares', NULL, 'In a dihybrid testcross of an individual with AB/ab genotype and an individual with ab/ab, the following phenotypic ratios were observed: 420 AB, 80 Ab, 70 aB, 430 ab. What is the recombination frequency between A and B?', '["7%", "15%", "23%", "50%"]'::jsonb, 1, '15%', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false);
