-- Part B: Heredity -- batch 1/5
INSERT INTO quiz_questions (event_id, topic, subtopic, question, options, correct_index, correct_answer_text, explanation, difficulty, question_type, points, source_tournament, ai_generated)
VALUES
INSERT INTO quiz_questions (event_id, topic, subtopic, question, options, correct_index, correct_answer_text, explanation, difficulty, question_type, points, source_tournament, ai_generated)
VALUES
  ((SELECT id FROM events WHERE name = 'Heredity'), 'RNA Structure and Function', NULL, 'Which base is found in RNA but not in DNA?', '["Thymine", "Adenine", "Cytosine", "Uracil"]'::jsonb, 3, 'Uracil', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'Sex-Linked Inheritance', NULL, 'Hemophilia B is caused by a mutation in which gene?', '["Factor VIII", "Factor IX", "Factor V", "Factor XII"]'::jsonb, 1, 'Factor IX', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'RNA Structure and Function', NULL, 'The enzyme responsible for synthesizing RNA during transcription is:', '["DNA polymerase", "RNA ligase", "RNA polymerase", "Helicase"]'::jsonb, 2, 'RNA polymerase', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'Chromatin Structure', NULL, 'Which type of chromatin is more tightly packed and generally inactive?', '["Euchromatin", "Heterochromatin", "Polychromatin", "Metachromatin"]'::jsonb, 1, 'Heterochromatin', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'PCR', NULL, 'PCR works by cycling through which series of steps?', '["Denaturation \u2192 Annealing \u2192 Extension", "Initiation \u2192 Elongation \u2192 Termination", "Unwinding \u2192 Splicing \u2192 Translation", "Replication \u2192 Proofreading \u2192 Repair"]'::jsonb, 0, 'Denaturation → Annealing → Extension', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'Mendelian Genetics', NULL, 'Mendel’s Law of Segregation states that:', '["Genes on the same chromosome are inherited together", "Alleles segregate during gamete formation, so each gamete carries only one allele", "Some alleles are dominant while others are recessive", "Traits are blended in offspring"]'::jsonb, 1, 'Alleles segregate during gamete formation, so each gamete carries only one allele', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'Punnett Squares', NULL, 'In a cross Aa × Aa, what is the expected genotypic ratio of the offspring?', '["1:2:1", "3:1", "1:1", "9:3:3:1"]'::jsonb, 0, '1:2:1', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'Dominance and Gene Interactions', NULL, 'Which of the following is an example of codominance?', '["Red flower \u00d7 white flower = pink flower", "Blood type AB", "Black fur dominant over white fur", "Height in humans"]'::jsonb, 1, 'Blood type AB', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'Epistasis', NULL, 'Recessive epistasis occurs when:', '["A dominant allele masks a recessive allele", "Two dominant alleles interact to create a new phenotype", "A homozygous recessive allele at one locus masks the expression of another gene", "Two genes are inherited independently"]'::jsonb, 2, 'A homozygous recessive allele at one locus masks the expression of another gene', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'Pedigree Analysis', NULL, 'A pedigree shows a trait appearing in every generation. This suggests the trait is likely:', '["Autosomal recessive", "Autosomal dominant", "Sex-linked recessive", "Sex-linked dominant"]'::jsonb, 1, 'Autosomal dominant', NULL, 'easy', 'multiple_choice', 1, 'Badger Invitational 2025', false);
