-- Part D: Heredity -- batch 3/5
INSERT INTO quiz_questions (event_id, topic, subtopic, question, options, correct_index, correct_answer_text, explanation, difficulty, question_type, points, source_tournament, ai_generated)
VALUES
INSERT INTO quiz_questions (event_id, topic, subtopic, question, options, correct_index, correct_answer_text, explanation, difficulty, question_type, points, source_tournament, ai_generated)
VALUES
  ((SELECT id FROM events WHERE name = 'Heredity'), 'Translation', NULL, 'Which of the choices contains the areas of a cell in which protein synthesis occurs?', '["Nucleus and mitochondria", "Cytosol and rough endoplasmic reticulum", "Smooth endoplasmic reticulum and Golgi apparatus", "Smooth endoplasmic reticulum and rough endoplasmic reticulum"]'::jsonb, 1, 'Cytosol and rough endoplasmic reticulum', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'DNA Sequencing', NULL, 'Which of the following describes Sanger sequencing?', '["Uses RNA polymerase to make mRNA", "Incorporates dideoxynucleotides to terminate DNA synthesis at specific bases", "Amplifies DNA using thermal cycling", "Creates complementary RNA from DNA"]'::jsonb, 1, 'Incorporates dideoxynucleotides to terminate DNA synthesis at specific bases', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'General Genetics', NULL, 'A single base deletion in DNA may cause:', '["Missense mutation", "Nonsense mutation", "Frameshift mutation", "Silent mutation"]'::jsonb, 2, 'Frameshift mutation', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'Central Dogma', NULL, 'The central dogma of molecular biology states:', '["Protein \u2192 RNA \u2192 DNA", "DNA \u2192 RNA \u2192 Protein", "RNA \u2192 DNA \u2192 Protein", "Protein \u2192 DNA \u2192 RNA"]'::jsonb, 1, 'DNA → RNA → Protein', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'RNA Structure and Function', NULL, 'During transcription, RNA polymerase moves along:', '["5\u2019 \u2192 3\u2019 of the template strand", "3\u2019 \u2192 5\u2019 of the template strand", "3\u2019 \u2192 5\u2019 of the coding strand", "Randomly"]'::jsonb, 1, '3'' → 5'' of the template strand', NULL, 'medium', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'RNA Structure and Function', NULL, 'tRNA functions to:', '["Carry genetic information", "Carry amino acids to the ribosome", "Make peptide bonds", "Unwind DNA"]'::jsonb, 1, 'Carry amino acids to the ribosome', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'PCR', NULL, 'During PCR, denaturation occurs at:', '["50\u201360\u00b0C", "70\u201375\u00b0C", "94\u201398\u00b0C", "37\u00b0C"]'::jsonb, 2, '94–98°C', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'PCR', NULL, 'The role of primers in PCR is to:', '["Unwind the DNA", "Provide a starting point for DNA polymerase", "Cut DNA at specific sites", "Terminate synthesis"]'::jsonb, 1, 'Provide a starting point for DNA polymerase', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'PCR', NULL, 'Sanger sequencing differs from PCR because:', '["It uses RNA polymerase", "It uses dideoxynucleotides to terminate DNA synthesis", "It requires no primers", "It produces proteins"]'::jsonb, 1, 'It uses dideoxynucleotides to terminate DNA synthesis', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false),
  ((SELECT id FROM events WHERE name = 'Heredity'), 'PCR', NULL, 'PCR can be used to:', '["Amplify a specific DNA fragment", "Determine chromosome number", "Visualize ribosomes", "Transcribe RNA"]'::jsonb, 0, 'Amplify a specific DNA fragment', NULL, 'hard', 'multiple_choice', 1, 'Badger Invitational 2025', false);
